### ISSUE TITLE
Hidden config should be low level maintainable

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1011]
The `hidden.php` should be maintainable (at least download and upload, but best would also be by the integrated text editor) so that the user has at least the possibility to backup and fix things when some unknown bug in the editor or API creates a problem and he has no direct access to the file system.

This issue is a follow up from #1009

**Comment by peuter** [comment]
Can you provide a list of the currently used section/options in the hidden.php? Something we can create a JSON-Schema definition from.

**Comment by ChristianMayer** [comment]
See https://www.cometvisu.org/CometVisu/de/0.11/manual/config/hidden-config.html#bekannte-name-eintrage

The `name` can be chosen freely, the widget then has an attribute that tells what name to use.
(Reason: e.g. you might have multiple InfluxDBs that you wan to query, so it can't be hard coded)

**Comment by peuter** [comment]
That will be hard to validate in this kind of way. Can we add types to the name, e.g. influxdb type and the Schema is defined for the type?

**Comment by ChristianMayer** [comment]
I don't know what the validation needs or not. As it's our software we can do anything :)
Due to our users I would try hard to be backward compatible, though.

A few ideas to solve the issue:
- use "reserved"/"typical" names that can get validated and allow all others without validating
- use a prefix, so e.g. `/influx.*/` will be validated against the InfluxDB scheme and `/tr064.*|fritzbox.*/` against the tr064 scheme

**Comment by peuter** [comment]
A valid JSON scheme would look like this:

```json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "https://www.cometvisu.org/CometVisu/schemas/0.12/hidden-schema.json",

  "type": "object",
  "patternProperties": {
    "^fritzbox.*": { "$ref": "#/definitions/login" },
    "^influx.*": { "$ref": "#/definitions/login" }
  },
  "additionalProperties": false,

  "definitions": {
    "login": {
      "type": "object",
      "properties": {
        "uri":  { "type": "string", "format": "uri" },
        "user": { "type": "string" },
        "pass": { "type": "string" },
        "selfsigned": { "type": "string", "enum": ["true", "false"] }
      },
      "required": ["uri", "user", "pass"],
      "additionalProperties": false
    }
  }
}
```
Is it right that "uri", "user" and "pass" are always required?

**Comment by peuter** [comment]
Is there even a difference between the fritzbox theme and the influx theme? According to the manual they seem to be identical.
