### ISSUE TITLE
KNX back-end asks for unreadable group addresses on startup

### ISSUE THREAD

**Issue by smurfix** [CometVisu/CometVisu#1038]
I am the maintainer of knxd. I'm about to publish a new version which cleans up part of the HTTP interface that CometVisu uses.

While debugging the slowness of this process when CometVisu starts up, I noticed that it kindof violates the KNX specification. Specifically, there are group adresses which respond when you send a read request to them, and there are those which do not. It's a bad idea to actively send bus read requests to the latter addresses because nobody will answer anyway; worse, the bus adapter won't get an ACK for these messages, thus it unnecessarily sends each message two or three times.

It would be very helpful if you could add a flag to the KNX addresses that says whether they're to be included in the initial ("t=0") read request. This corresponds to the "L" flag in the ETS (presumably "R" when you switch it to English), which should be documented; if it isn't, its state is discoverable with the "knxtool" command.

NB: sometime early in 2021 I plan to rewrite knxd's HTTP back-end. While the current scheme will still be supported, the preferred (and faster, and much more reliable) method of accessing bus objects will be via a websocket.

**Comment by ChristianMayer** [comment]
I couldn't find in the specification (at least in the old release 3.0 that I have) that it is illegal to use the A_GroupValue_Read Service with a GA that has no L flag set. It actually says `Note: It is left to the user application programmer to decide whether an
A_GroupValue_Read.con time-out supervision is necessary.` so I guess the spec writers even had in mind that it could happen that such a request isn't answered - which, in the real world, could easily happen when a device or even a branch of the bus disappears.
Anyway, it's obvious that it doesn't make sense to read a non existing GA or one where no device has the L flag set. But it's neither our bus installation nor our visu configuration, it's that of the user - and users do strange things.

About a new transportation layer: WebSockets could also be added. But when server side events (SSE) would also be fine for you, please consider them, as they are already implemented and used in production (i.e. well debugged) for the OpenHAB communication -> https://github.com/CometVisu/CometVisu/blob/develop/client/source/class/cv/io/transport/Sse.js

**Comment by peuter** [comment]
As this flag actually already exists, I will close this issue.
As Christian already explained the CometVisu provides a possibility to mark a GA as "write-only" (thats what the mode-attribute is hanlding: https://github.com/CometVisu/CometVisu/blob/develop/source/resource/visu_config.xsd#L263-L272).

But we cannot rely that every user is using this correctly.
