### ISSUE TITLE
0.12.0-RC1: metal demo layout issues

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1108]
Opening the metal demo config and using different screen sizes (e.g. with the chrome mobile device emulation) different slight layout mishaps do occur:
![grafik](https://user-images.githubusercontent.com/10218721/149681544-4d19e013-2f8a-4f76-b120-e93648ae4041.png)

- sometimes(!) the color bar at the sliders aren't starting at the beginning (can be fixed by changeing pages back and forward)
- no space between the groups

![grafik](https://user-images.githubusercontent.com/10218721/149681581-b4102976-887b-4706-808f-790cc26a49ee.png)

Sometimes the issues come or go after a reload. Sometimes the page must be visible (or not) during reload

**Comment by peuter** [comment]
Is the misplaced sliders still a problem, I have never seen it. I need a way to reproduce it. If you cannot reproduce this either this issue can be closed because the other problems are fixed.

**Comment by ChristianMayer** [comment]
It's working fine during my current tests
