### ISSUE TITLE
0.12.0-RC1: Red window show stack trace, but not the error itself

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1117]
As can seen e.g. at https://forum.timberwolf.io/viewtopic.php?f=94&t=3274#p36943 in the screenshot

![](https://forum.timberwolf.io/ext/dmzx/imageupload/files/f6f5c425d595180984aeba38aca994cf.jpg)

a red error window is shown with a stack trace, but without the error itself.

**Comment by peuter** [comment]
Then there is no error message, all errors are captured in the same way and I do see error messages there. So it basically works but in this example there is nothing to show.
