### ISSUE TITLE
Fix dependabot messages

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1120]
https://github.com/CometVisu/CometVisu/security/dependabot shows currently a few issues. 
If possible they should be fixed (although they are not critical as only the build environment is affected)

**Comment by peuter** [comment]
The issues are related to dependencies of our dependencies. So unless the dependency we use does not provide a new version that fixes the problem there is nothing we can do about it. And as soon as there is such a new version, dependabot automatically creates a pull request for it.
