### ISSUE TITLE
0.12.0-RC3: Paste from external sources doesn't work in the editor

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1138]
Running on Chrome does work, but running exactly the same page on Firefox (and most likely also Edge) doesn't allow to paste text from a different source.
Pasting text copied from the editor window does work.

Page is served over HTTPS.

**Comment by peuter** [comment]
This is not fixable because firefox does not support the paste command, see: https://github.com/microsoft/azuredatastudio/blob/cb7b7da0a4bb2b45f0b6092e42fd1ca385938f09/src/vs/editor/contrib/clipboard/clipboard.ts#L29
