### ISSUE TITLE
0.12.0-RC3: opening editor fails

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1142]
See https://sentry.io/share/issue/e507e41aa3174dc2a4b2e75b008f7d63/
See https://forum.timberwolf.io/viewtopic.php?p=37090#p37010

**Comment by peuter** [comment]
This ticket does not contain any information about how to reproduce this error. Just a link to a closed forum I have no access to and a stacktrace from sentry.
