### ISSUE TITLE
0.12.0-RC3: sending bug report to sentry gives red popup

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1144]
Having a bug and creating the sentry message, this error shows up after a mouse click:
![grafik](https://user-images.githubusercontent.com/10218721/150572339-90d3502d-ced0-41a1-a424-e1ae7f02f605.png)

Note: this happens in Chrome with mobile device emulation active (i.e. sending touch events). Without emulation it's working.

**Comment by ChristianMayer** [comment]
Original problem where this issue happened on top: #1142

**Comment by peuter** [comment]
I just managed to reproduce it by:

1. loading the CV with `?config=demo&reporting=true`
2. Open the manager by clicking the link in the statusbar
3. Open a config file in source editor
4. Clicking into the source code at any place
5. => Error occurs
