### ISSUE TITLE
0.12.0-RC3: Konfigurations-Upgrader

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1147]
Nach https://forum.timberwolf.io/viewtopic.php?p=37090#p37010  :

> Starte ich dann den Konfigurations-Upgrader, kommt es zu folgendem:
> ![](https://forum.timberwolf.io/ext/dmzx/imageupload/files/30c42be00cce7f2ff0e374b050b94e14.jpg)

**Comment by peuter** [comment]
Isn' t this a duplicate of #1143

**Comment by ChristianMayer** [comment]
No, there it was wrongly linked

**Comment by ChristianMayer** [comment]
How does it come that ` at _enableSync/<(source/class/cv/io/openhab/Rest.js:385:74)` is in the stack trace of  COMETVISU-5M?
This was running on the TWS, so OpenHAB is not involved.

**Comment by peuter** [comment]
There is no `_enableSync` in openHABs Rest-Client, only in the Managers Rest-Client so the sourcemapping in the stacktrace must be wrong.

**Comment by ChristianMayer** [comment]
Cause is probably an issue with the (not yet released) TWS reverse proxy: https://forum.timberwolf.io/viewtopic.php?f=94&t=3274&p=37191#p37188

**Comment by ChristianMayer** [comment]
I guess we can close it as I don't know of any newer reports and it was most likely triggered by a faulty proxy
