### ISSUE TITLE
0.12.0-RC3: metal design: navbar hickups

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1149]
See https://forum.timberwolf.io/viewtopic.php?p=37145#p37145

> Beim Klicken auf "Technik2" im Navbar-Top und dann "Solar+Buffer" im Navbar-Left tritt ein Offset in der Darstellung auf, Screenshot2.
> Hängt aber auch von der Reihenfolge ab. Klick von "Main" auf "Technik2" ist ok, aber beim Aufruf von "Solar+Buffer" passt es nicht.
> Klickt man von "Main" auf "Technik1" und dann "Technik2" passt es unmittelbar nicht!
> 
> Außerdem durchdringt sich in diesen Fällen die Darstellung des Navbars-Left mit dem Statusbar unten.
> 
> Config liegt ebenfalls bei.

<img width="960" alt="Screenshot2" src="https://user-images.githubusercontent.com/10218721/150609836-55be858d-2370-45b0-a205-ff73b38c200f.png">

[visu_config_tablet_tws_css.zip](https://github.com/CometVisu/CometVisu/files/7916987/visu_config_tablet_tws_css.zip)

**Comment by ChristianMayer** [comment]
I can reproduce it with just the attached config.

Start -> Technik 2 is fine:
![grafik](https://user-images.githubusercontent.com/10218721/150640621-cf5313fa-66a1-41f4-b09d-b34f42df6320.png)

Startseite -> Technik 1 -> Technik 2 ist broken (top navbar missing; lower part looks strange):
![grafik](https://user-images.githubusercontent.com/10218721/150640542-2acc5c65-3149-4ebd-b63a-9d067d7269c5.png)

**Comment by peuter** [comment]
Nope, works fine in all sequences for me.

**Comment by ChristianMayer** [comment]
Can it be depending on screen size?

I've just opened it as it was in my browser and could see it there.
The forum post had this additional information:

> 1920x1080 auf 15" Display, Systemeinstellung für Schriftgröße 150%

**Comment by peuter** [comment]
Tested with 1920x1080 and a scaling of 100% and 200% (the only two options I have) and also with a 150% zoom in the browser. Still nothing wrong too see.

**Comment by peuter** [comment]
Ok got it, reducing the window height did the trick. Now I can reproduce it.
