### ISSUE TITLE
Manager UI logic: Implement history navigation

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1151]
See https://forum.timberwolf.io/viewtopic.php?p=37154#p37151

Obersvation:
> Wenn ich von meiner Visu den Manager aufrufe, bleibt die URL in der Browser Eingabezeile auf dem URL der Visu stehen. Ich kann dann im Manager eine andere Visu im Texteditor öffnen und die URL ist immer noch die alte.
> Ganz komisch wird es, wenn ich dann den Browser-Zurück Button verwende: Es ändert sich dann die URL, nämlich auf die alte URL mit id_x, der Unterseite der VIsu, die man zuvor angesehen hat. Allerdings: am Bildschirm bleibt die aktuelle Ansicht erhalten zB der Texteditor einer anderer Visu.

Reply:
> Der Manager ist nicht mehr eine extra Seite (so wie früher), sondern ein großes Popup über der aktuellen Seite.

Answer:
> Hab ich mir auch schon gedacht.
> 
> Nur sollte der Browser Zurück dann das pop-up schließen o.ä. so wie beim Diagramm Pop-up.

**Comment by peuter** [comment]
Implementing a history navigation in the manager is a complex task. Every navigation step needs to be translated into a URL for that and we have many variants of that in the manager. This is too complex for 0.12.0 and something for a later release.

**Comment by ChristianMayer** [comment]
Additional answer:

> Ok Danke.
> Wenn ich mich richtig erinnere war es beim Diagramm auch früher so, dass ein Zurück das Diagramm beibehalten hat.
> Das war verwirrend, aber durch die transparente Darstellung nicht ganz so schlimm. Wurde dann aber von Tobias erweitert, dass ein Seitenwechsel der Visu die Popups schließt (war glaub ich da mit drin: https://github.com/CometVisu/CometVisu/issues/862).
> 
> Beim neuen Manager finde ich es wesentlich irritierender, da man ja die Visu gar nicht mehr sieht. Somit sollte ein Browser zurück im Popup wirken und falls das nicht geht, entweder deaktivieren des Zurück-Buttons um Popup oder eben Popup schließen.
> 
> Wenn man es weiß, ist es auch nicht dramatisch, aber in jedem Fall ungewohnt und etwas unlogisch und für neue Benutzer potentiell verwirrend.
