### ISSUE TITLE
0.12.0-RC4: Wiregate is too old

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1157]
As the Wiregate comes with PHP 5.2.6 it's too old for the requirements of the new manager.
The documentation should be updated accordingly.

**Comment by peuter** [comment]
We should also add a simple php file somewhere that responds with its PHP version, so that the manager can check it and show an error message to inform the user that its too old.

**Comment by ChristianMayer** [comment]
The PR will have the file `/rest/manager/environment.php` that will respond with e.g.:
```
{"phpversion":"7.4.15","PHP_VERSION_ID":70415,"SERVER_SIGNATURE":"<address>Apache\/2.4.38 (Debian) Server at 127.0.0.1 Port 28080<\/address>\n","SERVER_SOFTWARE":"Apache\/2.4.38 (Debian)"}
```

This is just the start for a check. The check itself won't be in the PR.
