### ISSUE TITLE
SF#81 iOS scrolling

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#118]
(Imported from https://sourceforge.net/p/openautomation/bugs/81/)

iOS devices seem to have scrolling problems
-> see http://knx-user-forum.de/cometvisu/30418-iphone-scrolling.html

**Comment by ChristianMayer** [comment]
Last information from https://sourceforge.net/p/openautomation/bugs/81/

the fix has a regression:
"Ansonsten hab ich noch ein Samsung Galaxy ACE mit Android 2.3.5 mit integriertem Browser hier. Damit funktioniert das Scrollen leider nicht. Sobald ich scrolle, wird die vorher angezeigte Visuseite teilweise eingeblendet, aber es wird nicht gescrollt. Beim Loslassen des Fingers erschein wieder die aktuelle Visuseite komplett, es wurde aber nicht gescrollt."
Source: http://knx-user-forum.de/350930-post13.html

Bug is still open.

**Comment by ChristianMayer** [comment]
Is this still open?

As no fix was submitted so far -> postponed till next release

**Comment by alltime84** [comment]
my pull request might solve that problem: [enable scrollable navbarLeft on mobile devices](https://github.com/CometVisu/CometVisu/pull/261)

**Comment by ChristianMayer** [comment]
Is that still open?
