### ISSUE TITLE
0.12.0-RC5: MQTT backend breaks during logging

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1198]
At e.g. line 189 of the client a call like `self.log('Connection Lost: ...` is made.
But (with `self = this`) a `self.log` doesn't exist.

**Comment by peuter** [comment]
There is no `this.log` use `this.info` instead for the default log-level. See: https://www.cometvisu.org/CometVisu/en/latest/api/#qx.core.MLogging
