### ISSUE TITLE
SF#86 Display errors in Metal design with Android 4.0.4

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#120]
(Imported from https://sourceforge.net/p/openautomation/bugs/86/)

See http://knx-user-forum.de/351864-post7.html

**Comment by ChristianMayer** [comment]
Is this still open?

As no explicit fix was submitted so far --> postponed

**Comment by ChristianMayer** [comment]
No more information given, Android 4.0.4 is quite old now

**Comment by ChristianMayer** [comment]
@manoficons as this report was initially from you: does it work now? Can we close this issue?

**Comment by manoficons** [comment]
Working. Issue can be closed.
