### ISSUE TITLE
0.12.0-any: check demo configs prior to release

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1208]
All demo configs should be checked that they run smoothly prior to the final 0.12.0 release:
- all resources are available (e.g. counter in the widget demo; icon in the status bar)
- good display on smartphone screens (especially true for the widget demo)

**Comment by ChristianMayer** [comment]
- [x] Icon in the statusbar is fine

**Comment by ChristianMayer** [comment]
-  [x] resources should work now (with #1254 )

**Comment by peuter** [comment]
@ChristianMayer Can we close this now?

**Comment by ChristianMayer** [comment]
I think so. But I want to close it just prior to the release after a double check
