### ISSUE TITLE
SF#92 SVG animation not working properly in Chrome

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#122]
(Imported from https://sourceforge.net/p/openautomation/bugs/92/)

In Chrome (v27, v31) the animation in an SVG is not shown when navigating to the SVG-page after the "animation-active-GA" was triggered. The animation works in FF21.

see: http://knx-user-forum.de/cometvisu/20618-svg-fuer-heizung-11.html#post360455

**Comment by ChristianMayer** [comment]
Is this still open?

**Comment by mivola** [comment]
it still doesnt work for me in Chrome 51

**Comment by ChristianMayer** [comment]
OK, I put it to the list of active bugs. But post 0.10.0 as there's no fix available yet and it's not on my own priority list for 0.10.0

**Comment by mivola** [comment]
sure, it's no priority for me either - it's more a nice to have gimmick ...

**Comment by ChristianMayer** [comment]
@mivola chrome has seen a few more versions - is it still an issue?

**Comment by ChristianMayer** [comment]
Seems to work now.
