### ISSUE TITLE
0.12.0-RC6 : clock plugin does not work with Openhab as backend

### ISSUE THREAD

**Issue by catwiesel25** [CometVisu/CometVisu#1231]
As soon as the address is changed to "address transform="OH:number" mode="readwrite">time</address" the page will not load anymore.
![Cometvisu Fehler Clock](https://user-images.githubusercontent.com/95273126/156220620-1c29b735-0294-4fcc-b2f6-de8839aa1178.jpg)
![Cometvisu Fehler Clock_1](https://user-images.githubusercontent.com/95273126/156220657-be96e884-cf19-4e62-baca-f7236a96fb69.jpg)
[CometVisu-replay-20220301-182910.zip](https://github.com/CometVisu/CometVisu/files/8163693/CometVisu-replay-20220301-182910.zip)

**Comment by peuter** [comment]
The clock plugin expect the value to be in "HH:mm:ss" format, the only way to achieve this with openHAB-backend currently is when you use a string item which contains the value in that format and use the transform "OH:string".
But we definitely have to make the code more robust here, shouldn't throw an exception when the incoming data is not in the expected type.

**Comment by catwiesel25** [comment]
I have adjusted the item accordingly .
my item : `String Zeit`
I have preset the item with the value 11:11:11
my Clock plugin : `<clock src="plugins/clock/clock_full.svg" src_popup="plugins/clock/clock_full.svg" send_on_finish="true" hide_seconds_popup="true" hide_seconds="true" hide_am_pm_popup="true" hide_am_pm="true" hide_24h_popup="true" hide_24h="true">
      <layout colspan="2" rowspan="2"/>
      <address transform="OH:time" mode="readwrite">Zeit</address>
  </clock>`
Results in the following error message :
![Cometvisu Fehler Clock_2](https://user-images.githubusercontent.com/95273126/156410600-c27671ea-347f-4981-9cb2-3db7840d69b4.jpg)

**Comment by peuter** [comment]
That stacktrace does not really help, can you please check both checkboxes in the error dialog and hit "Neu laden" and provoke the error again. Then the stacktrace and an interaction log is sent to sentry and usually we have more options to investigate the error.
Other option is: Open the same config with the URL-Parameter "testMode=true" then no values are send / received from the openHAB backend. Then open the Developer Tools of the browser (with F12) goto the javascript console and enter `cv.TemplateEngine.getClient().write('Zeit', '11:11:11')` that is a simulation as if the value is coming from the backend. Does it work then?

**Comment by catwiesel25** [comment]
With "testMode=true" and writing the command into the JavaScript Console no error occurs and the time is displayed.
I also have the stacktrace and an interaction log sent to sentry.io.

**Comment by peuter** [comment]
Unfortunately there is no new error on sentry.io. I don't know why.

**Comment by peuter** [comment]
Yes its there, thanks.

**Comment by peuter** [comment]
Ok that error has alread been fixed, but after RC6 has been released, so you either try the latest nightly build or wait fpr 0.12.0-RC7 (I can't give a date when that one will be released)

**Comment by catwiesel25** [comment]
I've build a release of the Branche "release-0.12" and now it works as expected.

Thanks for the support!
