### ISSUE TITLE
0.12.0-RC6 and devel: firefox incognito doesn't load

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1234]
Opening the CV in Firefox incognito mode doesn't work with
- 0.12.0-RC6
- devel when `enableCache=true` is set

devel without cache does work.

=> I assume it's a caching / service worker issue

**Comment by peuter** [comment]
service worker is not used in devel, so it must be the cache. I guess its because the indexedb used by the cache is not available in private browsing mode in firefox due to a bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1639542
