### ISSUE TITLE
SF#97 rrd diagrams not updated 

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#124]
(Imported from https://sourceforge.net/p/openautomation/bugs/97/)

rrd-diagrams are not updated on:
- Android 4, Firefox and Chrome
- Windows Phone 8.1, based on IE
Valid for CV 0.8.3 and 0.8.4 (correct behaviour for 0.8.2)
As workaround page must be reloaded.
Deleting cache/offline-content does not help.

Bug was described and confirmed here:
http://knx-user-forum.de/434248-post17.html

**Comment by joltcoke** [comment]
With the recent fixes in develop, this works fine for me. IMHO this issue can be closed. Tested with openHAB backend only. YMMV

**Comment by joltcoke** [comment]
Should be fixed in 0.9.0
