### ISSUE TITLE
0.12.0-RC8: show faded navbar on big touch devices hardly working

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1250]
Having a big touch device (e.g. desktop with mobile emulation in the browser), opening the demo config it is possible (as intended!) to fade out the left navbar.
But it's quite hard to show it again.

Cause: `#centerContainer` has only 1px height. I.e. you must touch at the top horizontal orange line and you can show the navbar again.

So far I didn't find a simple solution that made the `#centerContainer` as tall as it needs to be. Except setting it `display:flex` - which causes some minor other display issues, like making the left navbar smaller than it should be.

**Comment by peuter** [comment]
If you need the correct height just add `class="clearfix"` to the centerContainer. But I don't see any difference in the behavior of the navbar fading when the centerContainer has a height. Tested in Chrome and Firefox and both behave the same. I do not have a problem to fade in the navbar multiple times in both browsers, even with the current implementation. Tested with the `metal`-demo config which has a left navbar on the KNX-page.
