### ISSUE TITLE
0.12.0-any: documentation: attribute lib_version in description of xml-Header missing

### ISSUE THREAD

**Issue by daywalker1180** [CometVisu/CometVisu#1257]
In current documentation releases:

Attribute lib_version is not listed but is required accoding to visu_config.xsd.
Also not shown in example line.
Should be "9" within v0.12.0 according to demo configuration (?).

https://www.cometvisu.org/CometVisu/de/0.12/manual/config/xml-format.html#xml-format-header
https://www.cometvisu.org/CometVisu/en/0.12/manual/config/xml-format.html#xml-format-header

**Comment by daywalker1180** [comment]
Also documentation of attribute `backend` is not correct, 
according to doc permitted values are: `knxd, openhab, mqtt`

according to visu_config.xsd:

```
 <xsd:attribute name="backend">
    <xsd:annotation>
      <xsd:appinfo>level:expert</xsd:appinfo>
    </xsd:annotation>
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <!-- Old values, kept for backwards compability -->
        <xsd:enumeration value="cgi-bin" />
        <xsd:enumeration value="oh" />
        <xsd:enumeration value="oh2" />
        <!-- New values, should be used now -->
        <xsd:enumeration value="default" />
        <xsd:enumeration value="openhab" />
        <xsd:enumeration value="openhab2" />
        <xsd:enumeration value="mqtt" />
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:attribute>
```
Note: indeed the attribute is optional...

**Comment by ChristianMayer** [comment]
@daywalker1180 thank you for the information :+1: 

A patch is in PR #1258 

The enumeration values can't be cleaned up without breaking a old config. So it's just deprecated to use those values at the moment. In the future we might remove the old values and increase the library version to make the config upgrade script help with that.
