### ISSUE TITLE
SF#11 I18N and L10N - Visu 

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#127]
(Import from https://sourceforge.net/p/openautomation/feature-requests/11/)

The visu (and thus it's config file) should allow to add lables et al. in multiple languages at the same time, that get selected on the browser settings

**Comment by peuter** [comment]
Qooxdoo has a builtin translation system, which can be used. But I don't know of any string in the sources that require translations (some error messages maybe?) and I don't see the need for translations in the config files as every user will use the language he prefers for his configs.

@ChristianMayer Is there anything that needs to be translated? Or can we close this issue as the possibility is now given.

**Comment by ChristianMayer** [comment]
There are a few error messages that should be translated. And I18n could be interesting for e.g. the info widget when it should display a date.
=> I wouldn't close that issue

**Comment by peuter** [comment]
Ok a translated the config file errors to german, are there other errors that are visible to the user? 
And l18n of dates can be done by the user using the format attribute, or am I wrong?

**Comment by peuter** [comment]
We have a working translation system now
