### ISSUE TITLE
SF#14 config check should work with custom widgets and plugins 

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#128]
(Imported from https://sourceforge.net/p/openautomation/feature-requests/14/)

The schema check is working against a static xsd that doen't know about custom widgets and plugins. This should be changed to show a valid XML even with custom objects.

**Comment by ChristianMayer** [comment]
Last message on SF:

Not fixable with the current static XSD.
Probably in future when the XSD might be generated dynamically.

**Comment by peuter** [comment]
That's what the <custom> tag is meant for, inside this tag no validation is done. If you pust custom widgets/plugin in there you still have a valid config.
