### ISSUE TITLE
Getting the demo configs gives 500 error

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1292]
Loading the demo config the browser shows in the console:
![grafik](https://user-images.githubusercontent.com/10218721/202871565-c4c2adb2-ac31-41bb-9c66-63116875cb3d.png)

The apache log on the server says:
```
[Sat Nov 19 21:03:55.736197 2022] [php:error] [pid 3532] [client 172.17.0.1:47818] PHP Fatal error:  Uncaught TypeError: Slim\\App::__construct(): Argument #1 ($responseFactory) must be of type Psr\\Http\\Message\\ResponseFactoryInterface, array given, called in /var/www/html/obiwan/rest/manager/lib/SlimRouter.php on line 250 and defined in /var/www/html/obiwan/rest/manager/vendor/slim/slim/Slim/App.php:61\nStack trace:\n#0 /var/www/html/obiwan/rest/manager/lib/SlimRouter.php(250): Slim\\App->__construct(Array)\n#1 /var/www/html/obiwan/rest/manager/index.php(108): OpenAPIServer\\SlimRouter->__construct(Array)\n#2 {main}\n  thrown in /var/www/html/obiwan/rest/manager/vendor/slim/slim/Slim/App.php on line 61, referer: https://timberwolf76.local/proxy/visugit/obiwan/?config=demo
```

**Comment by ChristianMayer** [comment]
This was discovered during the review of #1290, but it is not linked to it. 
It happens with code in the 0.12 banch (with qx6 installed) as well as in the current development branch (with qx7 installed)

**Comment by peuter** [comment]
If you switch between release-0.12 and development branch you need to make sure that you update the rest dependencies. They use different slim versions (release is version 3.x, develop is version 4.10). They are not compatible.

I see the error only when I switch to release branch and do not update the rest dependencies and that is no bug in the code but just wrong usage.

**Comment by ChristianMayer** [comment]
The issue was caused by a non fitting version of "slim".
If could be fixed by running `composer install` in the directory `source/rest/manager`
