### ISSUE TITLE
v0.12.x: Diagrams fail with "TypeError: t is undefined"

### ISSUE THREAD

**Issue by FireFlyVDR** [CometVisu/CometVisu#1312]
I'm running CometVisu 0.11.2 successfully under Apache/PHP 8.1 with openhab 3.x and influxdb.
I recently tried to upgrade CometVisu to 0.12.1 and all values are displayed correctly (so the connection to openhab/influxdb works) but none of the diagrams with data from InfluxDB are displayed but a TypeError appears. I also tried v0.12.0 with the same result.
I tried to debug this and found that influxfetch.php receives an answer of about 7kB of JSON data before the error message appears:

```
TypeError: t is undefined
 in file http://192.168.XXX.XXX/cv/index.js
 line 39
Normalized Stack:  
        http://192.168.XXX.XXX/cv/index.js:39:190704
        http://192.168.XXX.XXX/cv/package-3.js:1:5327
        http://192.168.XXX.XXX/cv/package-3.js:1:5006
        http://192.168.XXX.XXX/cv/index.js:14:523041
        http://192.168.XXX.XXX/cv/index.js:14:561674
        http://192.168.XXX.XXX/cv/index.js:14:523006
        http://192.168.XXX.XXX/cv/index.js:14:522912
        http://192.168.XXX.XXX/cv/index.js:14:484150
        http://192.168.XXX.XXX/cv/index.js:14:494623
        http://192.168.XXX.XXX/cv/index.js:14:561674
        http://192.168.XXX.XXX/cv/index.js:14:494582
        http://192.168.XXX.XXX/cv/index.js:14:496958
        http://192.168.XXX.XXX/cv/index.js:39:156714
        http://192.168.XXX.XXX/cv/index.js:39:156181
        http://192.168.XXX.XXX/cv/index.js:39:155759
        http://192.168.XXX.XXX/cv/index.js:14:491737
        http://192.168.XXX.XXX/cv/index.js:39:405488
        http://192.168.XXX.XXX/cv/index.js:39:409207
        http://192.168.XXX.XXX/cv/index.js:39:409003
        http://192.168.XXX.XXX/cv/index.js:14:394921
        http://192.168.XXX.XXX/cv/index.js:14:557028
```

**Comment by ChristianMayer** [comment]
As the release versions are minimized and packaged that stack trace doesn't help locating the affected place.
When the error occured: did you get a red popup that let you upload the error to Sentry?
If that's the case, please do it. Then we have much better information about the error location.

**Comment by FireFlyVDR** [comment]
Yes, the TypeError message above is from the red popup.
I just reloaded the page and enabled Sentry, so you should have received it a minute ago

**Comment by peuter** [comment]
I am not able to reproduce the error mainly because I do not have a working influxdb setup where I can get data from. The error is either related to some weird timing issue during loading or related to the data that is loaded from the DB.
Both cases are almost impossible to reproduce in other setups.

The only chance we have is, if you enable both checkboxes in the error dialog to upload the error and the log file to sentry. Then I can replay the problem with the same timing and data and hopefully the error shows up in my development environment.

**Comment by FireFlyVDR** [comment]
Hopefully you have received now at least one report with interactions - the red dialog disappeared after about an second, so I added the option on the command line.
Let me know if you need any further data or if I should test some dev version before 0.12 to narrow down the error.
Btw: version 0.13-dev79 gives also an TypeError but with a different letter which I think is caused by different minimization.

**Comment by peuter** [comment]
Yes thanks, that did help to find the problem.
