### ISSUE TITLE
diagram scaling parameter has no effect

### ISSUE THREAD

**Issue by nipponichi111** [CometVisu/CometVisu#1374]
Release: v0.12.6
The "scaling" parameter has no effect to the diagram. The stored values in rrd are not multiplied with the scaling value.
v0.11.4 worked as expected.

Example (TeslaBatteryRange is given in m, TeslaEstimatedBatteryRange in km):

        <diagram width="250" height="175" popup="true" previewlabels="true" series="hour" refresh="60" period="12" title="Reichweite" legend="popup" legendposition="nw">
          <layout colspan="3"/>
          <axis unit="km" position="left" min="0" max="450">axis_km</axis>
          <rrd yaxis="axis_km" fill="false" steps="true" color="blue" scaling="0.001" consolidationFunction="AVERAGE" label="Ideal">TeslaBatteryRange</rrd>
          <rrd yaxis="axis_km" fill="false" steps="true" color="green" scaling="1" consolidationFunction="AVERAGE" label="Schätzung">TeslaEstimatedBatteryRange</rrd>
        </diagram>

**Comment by peuter** [comment]
The scaling / offset features do not seem to be implemented for openHAB backends. Do you use openHAB as a backend?

**Comment by nipponichi111** [comment]
Yes, I upgraded to OpenHab 4.0.3. However, with OH 3.0 it worked fine.

**Comment by peuter** [comment]
Well the openHAB version is unrelated to this issue, its the change of CometVisu versions that matter, we changed something in the implementation from 0.11 to 0.12 on how to handle data read from openHAB's persistance service and the scaling/offset feature got lost with that change.
