### ISSUE TITLE
Documentation hidden.php misleading

### ISSUE THREAD

**Issue by KomtGoed** [CometVisu/CometVisu#1388]
Hi,

(using 0.12.6 in container)

Was trying to create a hidden.php from scratch with a text editor as documented here: https://www.cometvisu.org/CometVisu/de/0.12/manual/config/hidden-config.html

After many sleepless nights (kidding, an hour or so), I created the file using the manager and it turned out the syntax should be as follows:
` "uri": "http:\/\/192.168.1.1:8086\/query",`

Instead of the non-escaped version from the documentation:
`    "uri": "https://172.17.0.1/proxy/ts/query",
`

Have I missed something? Or would it make sense to update the documentation?

**Comment by peuter** [comment]
It works for me without escaping the slashes in URLs, I will update the documentation because se use a slightly improved version (paring with try...catch block). But I cannot reproduce the described problem.

**Comment by KomtGoed** [comment]
Thanks for looking into this.
Just re-tested (without any other changes to the container) and indeed, I cannot reproduce the problem as well...
Maybe I did some other configuration error back then.

Sorry for the hassle and happy holidays
