### ISSUE TITLE
Build system / CI issues

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1405]
Many entries like `file external/knx-uf-iconset/raw_svg/audio_audio.svg has too many elements` starting from
https://github.com/CometVisu/CometVisu/actions/runs/8608742944/job/23802504511#step:13:49

Many entries like `Internal Error (overlap) in uniEE75: monotonic is both needed and unneeded (647.667,363.838)->(647.625,364.706). x=647.646 (prev=365.998)` starting from
https://github.com/CometVisu/CometVisu/actions/runs/8608742944/job/23802504511#step:13:908

18 warnings at https://github.com/CometVisu/CometVisu/actions/runs/8608742944

**Comment by peuter** [comment]
Those would need to be fixed in the icon source SVGs and not on our side. The SVG source of the icons is not really clean and it has been very hard to find the right amount of optimizations to get rid of the visual errors.

**Comment by ChristianMayer** [comment]
I don't think we can do anything about the SVG upstream as it's directly exported out of Adobe Illustration IIRC.

Probably there are some filters / enhancers / cleaners that we can use as a preprocessor?

**Comment by peuter** [comment]
> Probably there are some filters / enhancers / cleaners that we can use as a preprocessor?

I tried really many of them, the current result is the best I could find. I solves all the real visual errors and just leaves this warnings. And after putting so much time into this topic I don't feel the need to put even more into it, just to get rid of some warnings (which, most likely, might not be possible).
