### ISSUE TITLE
SF#72 wgplugin_info: mapping styling und format fehlen 

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#142]
(Imported from https://sourceforge.net/p/openautomation/feature-requests/72/)

wgplugin_info erweitern, so dass mapping styling und format tags unterstützt werden

"align" vergessen, funktioniert derzeit auch nicht

**Comment by ChristianMayer** [comment]
Noch kein Code -> postpone

**Comment by ChristianMayer** [comment]
As it's not implemented right now -> move to post 0.11.0

**Comment by ctr49** [comment]
Ist das wirklich noch offen?
Ich habe mehrere wgplugin_info widgets bei denen styling und format wunderbar funktionieren.

**Comment by ChristianMayer** [comment]
Yes, this should work now.
