### ISSUE TITLE
"clickable group" does not work in git version

### ISSUE THREAD

**Issue by jensgulow** [CometVisu/CometVisu#152]
For further information see here:

http://knx-user-forum.de/forum/supportforen/cometvisu/825432-clickable-group-in-aktueller-git-version-benutzbar#post825432

**Comment by jensgulow** [comment]
The fix above does not solve the problem

**Comment by jensgulow** [comment]
Am 09.04.2015 um 18:25 schrieb Christian Mayer:
>
> Closed #152 <https://github.com/CometVisu/CometVisu/issues/152> via 
> 0c549da 
> <https://github.com/CometVisu/CometVisu/commit/0c549da871ab5887ad62ddbee6f4477975af36f3>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CometVisu/CometVisu/issues/152#event-277334504>.
>
> E-Mail ist virenfrei.
> Von AVG überprüft - www.avg.de <http://www.avg.de>
> Version: 2015.0.5863 / Virendatenbank: 4328/9493 - Ausgabedatum: 
> 09.04.2015
>
Funktioniert noch nicht - ich kann aber das issue nicht wieder eröffnen, 
da es von einem Repo-Verantwortlichen geschlossen wurde. Bitte wieder 
öffnen.
Danke

**Comment by ChristianMayer** [comment]
> Funktioniert noch nicht - ich kann aber das issue nicht wieder eröffnen,
> da es von einem Repo-Verantwortlichen geschlossen wurde.

Wieder etwas gelernt

> Bitte wieder
> öffnen.

Done

**Comment by jensgulow** [comment]
Dankeschön, mittlerweile durch peuter mit pull-request #161 gefixt.
