### ISSUE TITLE
Info without label shows "undefined" as label

### ISSUE THREAD

**Issue by DirkHedderich** [CometVisu/CometVisu#17]
New error occurs in develop: If an "info" element contains no label the visu shows "undefined" instead.
In previous versions it was ok to leave the label empty, please see attached screenshots.
![visu major](https://cloud.githubusercontent.com/assets/10908151/6098488/6ee61c9a-afe0-11e4-889f-315491a10283.png)
![visu dev](https://cloud.githubusercontent.com/assets/10908151/6098489/77955a18-afe0-11e4-9c25-b1d8266d126a.png)

The xml is the same file:

			<info mapping="DoorOpenClose">
				<layout colspan="1"/>
				<label>Tor</label>
				<address transform="DPT:1.001" mode="read">3/2/5</address>
			</info>
			<info mapping="DoorOpenClose">
				<layout colspan="1"/>
				<address transform="DPT:1.001" mode="read">3/2/4</address>
			</info> 

![Uploading Visu Major.png . . .]()
![Uploading Visu Dev.png . . .]()

**Comment by ChristianMayer** [comment]
Confirmed. This should be fixed by the latest pull (#21).

**Comment by ChristianMayer** [comment]
When it's working for you: please close this isse
