### ISSUE TITLE
rsslog popup faulty (android chrome)

### ISSUE THREAD

**Issue by XueSheng-GIT** [CometVisu/CometVisu#180]
originally reported @ http://knx-user-forum.de/forum/supportforen/cometvisu/41590-code-umstellung-zur-performance-optimierung?p=682368#post682368

rsslog popup does not work properly when using android chrome.
Steps to reproduce:
1. open CometVisu (config with rsslog) with android chrome
2. tap on rsslog

Expected behaviour:
=> popup of rsslog should appear.

Actual behaviour:
=> popup does appear for just a few milliseconds, but disappears again.

**Comment by ChristianMayer** [comment]
Is that still an issue?
