### ISSUE TITLE
tap on pagejump triggers unexpected touch/hover (android chrome)

### ISSUE THREAD

**Issue by XueSheng-GIT** [CometVisu/CometVisu#181]
originally reported @ http://knx-user-forum.de/forum/supportforen/cometvisu/41590-code-umstellung-zur-performance-optimierung?p=682368#post682368

When using android chrome, tapping on pagejumps triggers unexpected "touch events".

Steps to reproduce:
1. open CometVisu (e.g. ?config=metal) with android chrome
2. on first page "Übersicht" tap on pagejump "Modus"
3. new page appears (pagejump "Wohnzimmer" is now visible and nearly at the same position as "Modus" before)

Expected behaviour
=> Just follow the pagejump without invoking additional touch/hover events.

Actual behaviour
=> pagejump is executed but it seems that another touch/hover event is invoked too.
=> "Wohnzimmer" is marked blue for a short moment.

Attached screenshots shows another example with a pagejump "Lüftung" and underlying diagram (touch on pagejump is passed to the popup diagram so that tooltip appears).
screenshot_1.jpg shows pagejump and new page with diagram
screenshot_2.jpg shows pagejump and diagram positioned on top of each other for better understanding.

![screenshot_1](https://cloud.githubusercontent.com/assets/4077683/7572114/3e879c3e-f81c-11e4-8980-41f1b98f98b3.jpg)
![screenshot_2](https://cloud.githubusercontent.com/assets/4077683/7572115/42c90f9e-f81c-11e4-80d2-a39330363e25.jpg)

**Comment by ChristianMayer** [comment]
@XueSheng-GIT is this still open?
(If yet: how severe? what milestone?)
