### ISSUE TITLE
touch event slider-range (android chrome)

### ISSUE THREAD

**Issue by XueSheng-GIT** [CometVisu/CometVisu#182]
originally reported @ http://knx-user-forum.de/forum/supportforen/cometvisu/41590-code-umstellung-zur-performance-optimierung?p=682368#post682368

On mobile (touch) devices the CometVisu pages are scrolled up/down with wipe events. slider-handle gets focus, even if you just want to scroll the page.

Steps to reproduce:
1. open CometVisu (config with slider) with android chrome
2. start to tap and hold your finger at the position of a slider-range (not slider-handle!)
3. move finger up/down to scroll page

Expected behaviour:
=> page scrolls up/down
=> slider is not triggered

Actual behaviour:
=> slider-handle gets focus and is moved (and undesired action is triggered)

Proposal for touch event of slider-range:
=> Single tap on slider-range should trigger an action
=> touch and hold should not trigger any action (so that page scroll is possible)

**Comment by ChristianMayer** [comment]
@XueSheng-GIT is this still open?
