### ISSUE TITLE
der Trigger kann kein Status anzeigen?

### ISSUE THREAD

**Issue by lo4dro** [CometVisu/CometVisu#189]
Hallo,

für die Umschaltung unterschiedlicher funktionen, benötige ich einen Trigger, der auch Statusmeldunen anzeigen kann.
Momentan wird immer nur der Trigger Wert als Status angezeigt.

**Comment by ChristianMayer** [comment]
@lo4dro Ein Trigger ist ein reines Fire&Forget Bedienelement. Wie ein Taster an der Wand.
Der hat somit keinen Status.

=> Was brauchst Du genau? Ist ein anderes Widget evtl. besser geeignet?

**Comment by peuter** [comment]
Keine Antwort -> closed
