### ISSUE TITLE
XML Kommentare werden beim Speichern gelöscht

### ISSUE THREAD

**Issue by murelli146** [CometVisu/CometVisu#190]
XML Kommentare die mit einem XML-Editor geschrieben wurden, werden beim Abspeichern mit dem CV-Editor entfernt.

**Comment by ChristianMayer** [comment]
Da es noch keine Implementierung gibt -> post 0.10.0

**Comment by ChristianMayer** [comment]
Da es noch keine Implementierung dafür gibt: Umzug nach nach Post 0.10.0
