### ISSUE TITLE
Request: Diagram closable via [x]

### ISSUE THREAD

**Issue by tuxedo0801** [CometVisu/CometVisu#213]
Pls. add a [X] button to the diagram-popup, which clearly indicates how to close it.
On small devices it's not so easy to find the point on the border to close it. An [x] would make it clear where to click.
See: http://knx-user-forum.de/forum/supportforen/cometvisu/39658-0-8-3-diagramm-popup-l%C3%A4sst-sich-nicht-schlie%C3%9Fen

**Comment by ChristianMayer** [comment]
Pull request #231 to solve this issue is active now.

**Comment by ChristianMayer** [comment]
As the request is pulled now, @tuxedo0801 can you please check and close this issue when it solves it?

**Comment by peuter** [comment]
Done
