### ISSUE TITLE
Request: Touch-enabled diagram-plugin

### ISSUE THREAD

**Issue by tuxedo0801** [CometVisu/CometVisu#214]
Scroll+Zoom on mobile devices is is not possible. Maybe find a way to implement it or search for an alternative chart-api that supports touch input?!

See: http://knx-user-forum.de/forum/supportforen/cometvisu/39658-0-8-3-diagramm-popup-l%C3%A4sst-sich-nicht-schlie%C3%9Fen

**Comment by cool-runnings** [comment]
I tried to solve this with Pull Request #363.

**Comment by ChristianMayer** [comment]
@tuxedo0801 is this issue fixed now? Can we close it?

**Comment by peuter** [comment]
No response for over a year now -> closing
