### ISSUE TITLE
RSSLog Plugin - Google cache Problem bei externen RSS Feeds

### ISSUE THREAD

**Issue by rene54321** [CometVisu/CometVisu#219]
Hi,

Google cached seine RSS Feeds über die Google Feed API. Somit wird ein externer RSS Feed trotzdessen er sich ändert in der Cometvisu nicht aktualisiert da die Google Feed API immer noch den gecachten verwendet. Um dieses Problem zu behen habe ich die rsslog_external.php angepasst so dass sich bei jeden Aufruf die Feed Adresse ändert (durch hinzufügen der aktuellen Zeit+Datum). Somit denkt die API einenen neuen Feed zu bearbeiten und greift auf keinen alten zwischengespeicherten zu.

Code:

<?php
/****************************************************************************_/
/_ rsslog_external.php - A simple wrapper to fetch cross-domain content      _/
/_ version 0.0.2                                                             _/
/_ (c) 2014 by ctr http://knx-user-forum.de/members/ctr.html                 _/
/_ Licenced under the GPLv3                                                  */
/*****************************************************************************/

$datum = date("H:i:s-d.m.Y");
$link = ($_GET["url"]);
$link = $link . '?' . $datum;

$json_url = 'https://ajax.googleapis.com/ajax/services/feed/load?v=1.0&num=1000&q=' . $link . '&output=json';

header('Content-type: application/json; charset=utf-8');
$str = preg_replace('/\\u003c.*?\\u003e/', '', file_get_contents($json_url));
echo strip_tags($str);
?>

mfg René

**Comment by ChristianMayer** [comment]
Hallo René,

kannst Du das auch als Pull-Request einstellen?

Dann könnte ich den einfach mergen.

**Comment by ChristianMayer** [comment]
@rene54321 @ctr49 
Wie ist denn der aktuelle Status zu diesem Issue? Ist das noch aktuell?

**Comment by rene54321** [comment]
Hi,

funktioniert alles wieder wie es soll danke. Kann geschlossen werden
