### ISSUE TITLE
EDITOR: nach editieren im url Eingabefenster des urltrigger kommen oft zusätzlich Steuerzeichen in die config

### ISSUE THREAD

**Issue by tger977** [CometVisu/CometVisu#220]
siehe KNXUF:
http://knx-user-forum.de/forum/supportforen/cometvisu/880845-urltrigger-probleme-beim-eintrag-der-url-mittels-editor#post880845

Problem tritt immer dann auf wenn man in dem url Eingabefeld den String mittels DEL, ENTER oder BACK Taste bearbeitet. Dann scheinen Steuerzeichen mehrfach im url String in die Konfig übernommen zu werden ohne daß diese dann im Editor angezeigt werden und der link funktioniert dann im Betrieb nicht mehr...

**Comment by ChristianMayer** [comment]
Ist das noch gültig? Wie schwerwiegend?

**Comment by tger977** [comment]
Hi Chris,

habe ich nicht mehr weiter verfolgt, habe seit einiger Zeit auch die CV nicht mehr im Einsatz.

Gruß
Andi

**Comment by ChristianMayer** [comment]
In der aktuellen Git Version kann ich den Fehler nicht nachstellen (Test-Browser: Chrome).

Eigentlich erwarte ich hier aber kein anderes Verhalten als zur 0.9.0...

=> Bis ich den Fehler reproduzieren kann (z.B. mit detaillierter Anleitung) kann ich ihn nicht beheben
