### ISSUE TITLE
image widget lädt Inhalt auch wenn unsichtbar

### ISSUE THREAD

**Issue by grzlhmpf** [CometVisu/CometVisu#243]
Das Image Widget lädt die Grafik auch wenn es unsichtbar ist.

Dies macht Probleme besonders mit MJPEG wo der Stream startet (und aktiv bleibt) solange die CV im Browser geladen ist, auch wenn sie nie im Vordergrund ist.

sinnvolle Änderung: nur laden (und refreshen) wenn sichtbar.

**Comment by grzlhmpf** [comment]
aus SF#71

**Comment by ChristianMayer** [comment]
Pull request https://github.com/CometVisu/CometVisu/pull/267 is only adding infrastructure, it's not fixing this issue yet.  
=> Reopen

**Comment by ChristianMayer** [comment]
This is handled in #141
