### ISSUE TITLE
Vollständiges Refresh erzwingen

### ISSUE THREAD

**Issue by XueSheng-GIT** [CometVisu/CometVisu#249]
Das Refresh Widget löst zwar einen neuen Request aus (i=N), jedoch werden nicht alle GAs neu abgefragt (t=0).

Siehe Thread:
http://knx-user-forum.de/forum/supportforen/cometvisu/31897-status-update-ga-erzwingen?p=909183#post909183

**Comment by ChristianMayer** [comment]
Ist das jetzt gefixt und kann es geschlossen werden?

**Comment by XueSheng-GIT** [comment]
Request mit t=0 wird nun ausgeführt, wenn man das Refresh Widget betätigt. Habe dies aber nur kurz getestet. Falls es hier noch Probleme geben sollte, würde ich mich wieder melden.

**Comment by ChristianMayer** [comment]
Kann der Issue jetzt geschlossen werden?

**Comment by ChristianMayer** [comment]
No reaction for 3 weeks - assuming it's fixed now
