### ISSUE TITLE
Request (t=0) erzeugt mehrfach leere Antwort

### ISSUE THREAD

**Issue by XueSheng-GIT** [CometVisu/CometVisu#250]
Das Laden/Neuladen der CometVisu löst mehrere Requests mit t=0 aus, jedoch bleibt die Antwort leer. Bis zu 11 Anfragen ohne Rückmeldung konnten beobachtet werden.
Im Einsatz: Standard Wiregate mit developer CV.

Erwartung:
Request mit t=0 erhält zumindest partielle Antwort, so dass neuer Request mit i=N ausgelöst wird.

Siehe Thread:
http://knx-user-forum.de/forum/supportforen/cometvisu/31897-status-update-ga-erzwingen?p=907814#post907814

**Comment by XueSheng-GIT** [comment]
Da die Ladezeiten mittlerweile tatsächlich sehr nervig sind (bis zu 30 Sekunden, bis die Buswerte angezeigt werden), habe ich mir den Netzwerktraffic nochmals genauer angesehen.
Die angefügten Screenshots zeigen den Ladevorgang einmal mit rsslog und einmal ohne. Man kann deutlich erkennen, dass rsslog das Laden der Buswerte verhindert. Erst nachdem rsslog eine Antwort erhalten hat, stoppen die Requests mit t=0 und die Requests mit i=N starten!

![mit rsslog](https://cloud.githubusercontent.com/assets/4077683/12959931/f7c24448-d038-11e5-8293-b54db0c56f2a.png)
![ohne rsslog](https://cloud.githubusercontent.com/assets/4077683/12959934/fa9a8af4-d038-11e5-82a0-1fa490e00bf3.png)

**Comment by mivola** [comment]
Das Problem mit rsslog kann ich bestätigen. Seitdem ich letzte Woche meine RSS-DB komplett gelöscht habe, lädt die Visu wesentlich schneller.

**Comment by ChristianMayer** [comment]
Interessanter Fund!

**Comment by ChristianMayer** [comment]
Ich kann das gerade nicht nachvollziehen - weder im Code noch im Versuch.

Kannst Du per Wireshark die TCP Pakete mitschneiden und checken ob wirklich der Browser die "r"-Requests abbricht oder ob es der Server ist, der leere Antworten verschickt?

Bei ersterem müssten wir im JavaScript Code suchen, bei letzterem im eibread-cgi.c Code...

**Comment by XueSheng-GIT** [comment]
...für Wireshark brauche ich einen Moment.
Ich vermute das Problem tritt nur auf, wenn sich das rsslog auf der Startseite der Visu befindet! War das in Deinem Versuch auch der Fall?

Mir kam gerade wieder in den Sinn, dass die langen rsslog Ladezeiten kein neues Problem sind. Hauptproblem ist wohl die alte sqlite Version auf dem Wiregate. In folgendem Thread hatte ich mal einen Workaround gefunden:
http://knx-user-forum.de/forum/supportforen/cometvisu/31294-%E2%88%9A-ladezeit-cometvisu-rsslog-php?p=520072#post520072

Mit dem zusätzlichen Index läd rsslog wieder in wenigen Millisekunden (600ms, um genau zu sein). Dadurch kommt es auch zu keiner Verzögerung beim Laden der Buswerte.

**Comment by ChristianMayer** [comment]
Gibt er inzwischen mehr Infos? Ist das für die 0.10.0 ein Show Stopper?

**Comment by XueSheng-GIT** [comment]
Das Problem scheint sich mit der aktuellen git Version verschlimmert zu haben. Bei Laden der Visu kann es passieren, dass nur leere Antworten auf die Anfrage mit t=0 kommen (wiederholt sich jede Minute, watchdog?).

Hier ein aktueller Screenshot der Anfragen:

![bustelegram](https://cloud.githubusercontent.com/assets/4077683/22778456/43491c50-eeb7-11e6-9622-317aa2811ef6.png)

**Comment by ChristianMayer** [comment]
Welche eibd bzw. knxd-Version nutzt Du? Die vom WireGate oder eine andere/neuere?

**Comment by XueSheng-GIT** [comment]
Standard wiregate eibd.

**Comment by ChristianMayer** [comment]
@XueSheng-GIT  Das sollte mit 0.10.x gelöst sein?
Falls ja: bitte Issue schließen.

Außerdem: kannst Du mit der aktuellen develop (also der zukünftigen 0.11) nochmal testen - hier hat sich ja sehr viel im Hintergrund getan, nicht dass wir hier in eine Regression laufen...

**Comment by XueSheng-GIT** [comment]
Die letzten Änderungen in 0.10.x haben das Problem minimiert. Sporadisch kommt es vor, dass sich die Anfragen mit t=0 noch häufen. Da ich keine Zeit habe, mir das weiter anzusehen, schließe ich den Issue.
