### ISSUE TITLE
Use icons as webfonts

### ISSUE THREAD

**Issue by peuter** [CometVisu/CometVisu#251]
It is possible to create a webfont from the used svg icons. The main advantage of this feature would be that all icons can be scaled and colored easily (just like a font), it would decrease the size of the cometvisu package as the png versions of the icons wouldn't be needed anymore.

The webfont generation is quite easy done via grunt as you can see here https://github.com/peuter/knx-uf-iconset (just a quick proof-of-conecpt, needs some finetuning).

What needs to be done is configuring the build process for the special needs of the cometvisu 
and change the iconhandler to use the icons from the webfont.

**Comment by ChristianMayer** [comment]
Icons are now in a unified SVG. Can this issue be closed?

**Comment by peuter** [comment]
Actually I do not remember why I re-opened this issue and I am not aware of any problems, so I close it.
