### ISSUE TITLE
Error in infotrigger?

### ISSUE THREAD

**Issue by peuter** [CometVisu/CometVisu#255]
From my understanding the infotrigger mixes up the absolute/relative change mode, please ahev a look at:
https://github.com/CometVisu/CometVisu/blob/develop/src/structure/pure/infotrigger.js#L107

I guess it should be:
`if( !data.isAbsolute )`

Or am I getting something wrong here?

**Comment by ChristianMayer** [comment]
Can you tell me the application example where the behaviour seems to be wrong?

To be precise about the desired function:
- Absolute means the result is calculated internally and then sent out
- Relative is like the usual KNX Dim objects where the button just sends the Delta and the actor calculates the result and sends it

**Comment by peuter** [comment]
I have no example just stumbled upon it in the code. Obviosly I didn't knew the absolute/relative thing.
