### ISSUE TITLE
0.9.1/0.9.2: datasourceIndex funktioniert in Diagrammen nicht

### ISSUE THREAD

**Issue by grzlhmpf** [CometVisu/CometVisu#303]
0.9.0 war ok, Firefox ebenfalls ok.

`
<diagram width="600" height="300" series="hour" period="24" refresh="300" popup="false" previewlabels="true" legend="none" legendposition="nw">
             <layout colspan="6" />
             <label>Temperatur (letzte 24h)</label>
             <axis unit=" °C"/>
             <rrd datasourceIndex="0">linknx_vorgarten</rrd>
          </diagram>
          <diagram width="600" height="300" series="hour" period="24" refresh="300" popup="false" previewlabels="true" legend="none" legendposition="nw">
             <layout colspan="6" />
             <label>Feuchte (letzte 24h)</label>
             <axis unit=" %"/>
             <rrd datasourceIndex="1">linknx_vorgarten</rrd>
          </diagram>
`

Safar stellt nur datasource 0 dar:
![bildschirmfoto 2016-03-30 um 19 27 43](https://cloud.githubusercontent.com/assets/16964404/14226359/59706be6-f8e0-11e5-895b-f6ebc0bfc7de.png)

Firefox ist korrekt:
![bildschirmfoto 2016-03-30 um 19 27 56](https://cloud.githubusercontent.com/assets/16964404/14226360/5971feca-f8e0-11e5-8753-9f7124d10718.png)

**Comment by grzlhmpf** [comment]
mit 0.9.2 funktioniert es jetzt auch mit Firefox und Co nicht mehr!

**Comment by ChristianMayer** [comment]
Ist das ein Showstopper für die 0.10.0 oder kann es auf post 0.10.0 gesetzt werden?
