### ISSUE TITLE
AppCache

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#332]
Chrome will remove AppCache support over HTTP (to force people to migrate to HTTPS; https://bugs.chromium.org/p/chromium/issues/detail?id=588931) and Firefox will remove it entirely (https://www.fxsitecompat.com/en-CA/docs/2016/application-cache-support-will-be-removed/)

When that stabilizes we should move away from AppCache, e.g. towards Service Workers (https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API)

**Comment by peuter** [comment]
Isn't this a duplicate of #450 ?

**Comment by ChristianMayer** [comment]
You are right, there's a big overlap - so I'm closing this.
