### ISSUE TITLE
Switch Stop updating State

### ISSUE THREAD

**Issue by eslafur** [CometVisu/CometVisu#334]
Backend OpenHAB 1.8.1 with CometVisu Plugin
Server: openSUSE Leap 42.1
Versions: #304 #305 #333 
Browser: Chrome, internet Explorer, Firefox
windows 7 + 10

after 1-3 State changes (doesn't matter if pressed or BUS changed state) the State of buttons won't get  updated anymore. (not by updates and not by pressing)
if it gets pressed, the command get's send to the BUS every time by json requests:
`http://[Server]/services/cv/w?s=undefined&a=[ITEM]&v=OFF&ts=1462973947635`

sometimes by clicking (just before it happens) Chrome Throws the following Exception:
`GET http://[server]/services/cv/r?s=undefined&a=[item1]&a=[item2]&i=1462973301904 net::ERR_INCOMPLETE_CHUNKED_ENCODING`

in the releases 0.9.1 and 0.9.2 the same configuration works fine.

**Comment by ChristianMayer** [comment]
@eslafur Is this issue still open?

**Comment by eslafur** [comment]
@ChristianMayer just checked, with the latest Develop Branch (after merging 456) and openHAB and addon Updated to 1.8.3
the issue still remains.
tested on Default Configuration with a switch added.

Changes to default configuration made: 
`<pages backend="oh" [...]`
`<switch mapping="On_Off">
     <address transform="OH:switch" mode="readwrite">OG_09_licht_1</address>
</switch>`

the first action always works, the second one gets executed but not updated and the 3rd action throws while being executed:
`jquery.js:9203 GET http://openhab/services/cv/ws=undefined&a=OG_09_licht_2&v=ON&ts=1483884213571 net::ERR_INCOMPLETE_CHUNKED_ENCODING`

**Comment by ChristianMayer** [comment]
@peuter can you have a look and decide if that'll be fixed for 0.10.0 or whether it should be postponed. Please adjust the milestone accordingly.

**Comment by peuter** [comment]
Actually I tend to believe that this is more a backend problem, I remember that sometimes the OH1 backend sends invalid JSON as response, so the frontend does not have the correct state and the switch cannot toggle anymore. 

@eslafur Can you post the JSON response here, when the CHUNKED_ENCODING error appears, to make sure that I am on the right track?

There is a possible fix for this in the new code base, but it cannot be backported as is but must be re-written. Before I do that I need to now if this is really the error we are talking about here.

**Comment by eslafur** [comment]
![chrome_2017-01-11_14-36-14](https://cloud.githubusercontent.com/assets/16470950/21850571/8e321b80-d80b-11e6-9039-fe5e346e625c.png)
thats the Network history.

Request Header of failed response:
`GET /services/cv/w?s=undefined&a=OG_09_licht_2&v=ON&ts=1484141485422 HTTP/1.1
Host: openhab
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Authorization: Basic XXXXXXXXXXXXXXXXXXX==
Accept: application/json, text/javascript, */*; q=0.01
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
Referer: http://openhab/CV-Develop/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4`

Response Header
`HTTP/1.1 200 OK
Content-Type: application/json
Transfer-Encoding: chunked
Server: Jetty(8.1.3.v20120522)`

Chrome wouldn't let me Copy the Response itself.

I May also Grand Access to the Server files via a windows machine with TeamViewer.
If that would be helpfull you may contact me via   eslafur (at) gmail com

**Comment by peuter** [comment]
It is really the write request that fails? I was talking about the read request, which sometimes send invalid JSON data (e.g. multiple JSON-Objects in one string). The write always returns `{"success":1}` no chance to send something wrong there. Also the Content-Type in the response header looks weird `application/jsonv` is not a valid value. But that comes from the backend and cannot be the cause of this error, as you wrote that the CometVisu release versions are working fine.

@eslafur I would suggest to upgrade your backend to the last released 1.* version of openHAB maybe it helps, don't know just guessing. Or even better to OH2, cause the communication between the CometVisu and OH2 uses another technology which is way better and reliable than the old one.
I will try to reproduce your problem on the weekend but I am not very confident that I am able to, cause I used that setup (OH1 + CometVisu) for years and never had a problem exactly like yours.

**Comment by ChristianMayer** [comment]
What's the correct label / milestone for this issue now?

**Comment by peuter** [comment]
Sorry I am not able to reproduce or fix this til next release.

**Comment by peuter** [comment]
Please re-test with current development version

**Comment by eslafur** [comment]
I installed the newest version, the behavor has changed but is not fixed, random buttons won't update (while executing and sending the opesit state do openhab)  to exclude a Bad connection as the cause, i need to retry it tomorrow.

in chrome the network history still keeps a request to "/cv/r" pending.
https://youtu.be/mv1ye-MPX4A (images not jet in the directory)

I will also update every component involved tomorrow.

**Comment by peuter** [comment]
Did you test the latest release or the development version?
With development version you could try to record a logfile to document the wrong behaviour (described here http://cometvisu.org/CometVisu/de/latest/manual/colab/index.html#fehlerbericht-erstellen) and attach that file here.

**Comment by eslafur** [comment]
I was not Be able to Reproduce any behavior on a Fresh installations of openhab.
although the same versions have been used for installation, the OS and as CV Add-in.
Since the Problem seems to be somewhere else, I'll close the Issue.
