### ISSUE TITLE
Icons should follow text color

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#336]
Icons that have no specific color given should have the same color as the current text.

**Comment by ChristianMayer** [comment]
@peuter I'm thinking of changing the recolorable icons from a `<canvas>` to a `<div>` with the canvas as a background image to be hopefully able to use CSS as the deciding factor for the color used.

How could that be compatible with using a web font for the usual icons?

(Note: even when the web font is used for most of the icons the infrastructure for the icon recoloring is still necessary as the user could allways provide own icons that are not in the web font)

**Comment by ChristianMayer** [comment]
See also https://github.com/CometVisu/CometVisu/issues/251

**Comment by peuter** [comment]
Shouldn't be a problem, because using webfonts you only need a tag with some css to apply the webfont and the icon-character as text-content. In the current version it is done somehow like <i class="icon">[char]</i>. Could be easily changed to a div. I think is it even more compatible with webfont icons, as they are also colored by CSS.

**Comment by ChristianMayer** [comment]
OK, then I'll try an implementation

**Comment by ChristianMayer** [comment]
Hm, that also doesn't seem to work as intended. (I can make the color follow a class like "green" - but it doesn't follow the text color itself that might be changed somewhere. So it's also not (easily) possible for follow a text color change imposed e.g. by pressed vs. unpressed).

Next attempt: use SVG icons. https://sarasoueidan.com/blog/icon-fonts-to-svg/ ,  https://css-tricks.com/svg-sprites-use-better-icon-fonts/ and https://css-tricks.com/cascading-svg-fill-color/ et al. are talking about it beeing superior to icon fonts anyway...
