### ISSUE TITLE
Refactor startup code

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#337]
The current code and the events called during startup "is grown" and should be thoroughly refactored and documented.

Special tasks to take care of:
- Handling of delayed resource availability (e.g. backdrop image)

**Comment by ChristianMayer** [comment]
This should also consider when and how the handleResize is called.

**Comment by ChristianMayer** [comment]
Pull request https://github.com/CometVisu/CometVisu/pull/342 addresses the handleResize. But it can be done more thoroughly

**Comment by ChristianMayer** [comment]
This should be done during a big code cleanup -> post 0.10.0

**Comment by ChristianMayer** [comment]
See also #121

**Comment by peuter** [comment]
IMHO this has been done in 0.11. Can we close this issue?

**Comment by peuter** [comment]
Done in 0.11
