### ISSUE TITLE
Diagrams don't show up with latest develop version

### ISSUE THREAD

**Issue by joltcoke** [CometVisu/CometVisu#351]
When using the latest develop version, all the diagrams will disappear. The diagram plugin itself is full working, data is fetched etc, the diagram is just not visible.

I've tracked it down to some inter dependency of left side nav bar combined with diagrams. Minimal repro config attached.
[visu_config_bug.xml.zip](https://github.com/CometVisu/CometVisu/files/314288/visu_config_bug.xml.zip)

**Comment by ChristianMayer** [comment]
Just to be sure: did this work with earlier versions? (When was the last time it worked?)

**Comment by joltcoke** [comment]
I've meanwhile narrowed it down the changeset 6471e98.

**Comment by joltcoke** [comment]
Any news on this issue. Should we revert the problematic changeset until we have a proper fix in place?

**Comment by rene54321** [comment]
Any news regarding this problems. I am encountered the same today :-(

**Comment by ChristianMayer** [comment]
I've just tried the minimal repro config. But it's working for me (latest Chrome; data source changed to one that I have)

=> @joltcoke  @rene54321  Is this still a confirmed bug?

**Comment by peuter** [comment]
No answer -> closing. If this is still a problem with current development version please comment here.
