### ISSUE TITLE
RFE: debian build framework

### ISSUE THREAD

**Issue by ctr49** [CometVisu/CometVisu#353]
Would it make sense to include the debian build framework for automated packaging? May we can ask Elabnet  if they would share the "rules" file of their latest package to have the same structure. Everything else should be straightforward.

**Comment by ChristianMayer** [comment]
@ctr49 is that issue solved now?
(If not: what's missing? What milestone?)

**Comment by ChristianMayer** [comment]
@ctr49 is that issue solved now?
(If not: what's missing? What milestone?)

Without feedback I'll close this issue for the next release as it's now nearly 2 years without an answer.

**Comment by ChristianMayer** [comment]
No feedback for 5 years => closing.

We also have Docker now which is also a sort of packaging.
