### ISSUE TITLE
Group address will not be written by editor when address has not be imported to wiregate

### ISSUE THREAD

**Issue by SirTobiIV** [CometVisu/CometVisu#414]
The editor will not save a KNX group address to the xml-file, if the address has not be imported to the wiregate.

That results in an error, that the address element is not valid xml and therefore the xml-file is not editable by the editor anymore.

Check KNx forum for details:
https://knx-user-forum.de/forum/supportforen/cometvisu/952620-visu_config-xml-l%C3%A4sst-sich-nicht-mehr-bearbeiten

**Comment by ChristianMayer** [comment]
Fix is PR #458 

Note: the real source of the problem can't be easily fixed as preventing a save of a config file that is non conforming can also be a bad idea - people could loose their work when they don't have time to fix the issued right now.

This solution allows them to load a non conforming config file after showing a warning message. When used with the non conforming address elements the editor seems to handle the situation nicely.

**Comment by peuter** [comment]
Closed by #458
