### ISSUE TITLE
Speech plugin

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#442]
For the ToDo list:

- Transform is missing - this will cause the readout of pure hex numbers when the eibd backend is used
- sometimes repeated messages are desired - probably the current check should be enhanced by a timeout
- It would be great to be able to use a mapping, i.e. only message numbers are sent over the bus and the mapping translates that to the message to read

**Comment by ChristianMayer** [comment]
Some more thought about that:

I think this plugin needs a bit more infrastructure that we don't have at the moment:
Currently all infos from the bus are considered to be states. So repeated calling of the `update` method causes no harm as the value is overwritten by itself.

But this plugin needs to handle an event. With no state at all.

The currently used `update` will not work to show only such events as it's also called during initial start up or when the bus has low traffic so that a time out happens and all addresses are requested again.

So I suggest to consider to enhance the `update` calls by an additional information: is this really an event or just a state update/reconfirmation.
The flag would be set to the first when the CometVisuClient got a bus reply just with the address of the plugin (or a few more), and it would be set to the later on the initial request or after a timeout (basically allways when the Client made a request with `t=0`...)

**Comment by peuter** [comment]
Good point, I already added a mechanism to skip the initial incoming data, but forgot about the reconnects after timeout. Will change the behaviour, that the CometVisuClient sets the dataReceived property to false after every (re-)connect (which means every `t=0`request in `long-polling`-mode and every `connect`.call in `sse`-mode)
