### ISSUE TITLE
AppCache vs. Service Workers

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#450]
It seems AppCache is getting disliked and Service Workers should be used instead.
https://developers.google.com/web/fundamentals/getting-started/primers/service-workers

**Comment by peuter** [comment]
IMHO the requirement of HTTPS for service workers is a problem. As the CometVisu usually runs in a local network I think most of the users do not use HTTPS and also are not able to use it.

**Comment by ChristianMayer** [comment]
That's correct and an absolute PITA. See also https://knx-user-forum.de/forum/supportforen/wiregate/1002391-https-bzw-ssl

Either we can make Google Chrome et all rethink the strict HTTPS requirements (unlikely) or we find a solution for serving HTTPS.

At the end I can only imagine that the CV gets an HTTPS requirement and the person or company that distributes or installs the CV has the task to fullfill that requirement :(

**Comment by ChristianMayer** [comment]
#549 was decided to be not included in 0.11.0 -> postpone
