### ISSUE TITLE
Remove zrssfeed from rss plugin and rsslog_external.php from rsslog plugin

### ISSUE THREAD

**Issue by ctr49** [CometVisu/CometVisu#461]
Both rss plugins depend on Google feed API that was finally turned off on January 10th.

- rss plugin was primarily meant to display extern rss feeds (via now also non-working zrssfeed)

- rsslog plugin was primarily meant to display the rsslog database, but was later extended to also display external feeds (which doesnt work either anymore).

I suggest to rewrite external rss feed support using a native rss2json in Javascript, but having above still in place will confuse users. So we should remove it.

For discussion also see:
https://knx-user-forum.de/forum/supportforen/cometvisu/34494-rss-vs-rsslog?p=1039458#post1039458

**Comment by peuter** [comment]
As we plan to refactor the CometVisu source code and base it on the qooxdoo Framework, which provides YQL support (https://developer.yahoo.com/yql/) I suggest to use that for external feeds (and other external data, as it it very powerfull). Downside is that we are again dependent from an external api, which might be closed in the future (like Google).

**Comment by peuter** [comment]
RSS should be replaced now with RssLog
