### ISSUE TITLE
Inconsistent caching behavior

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#469]
As seen e.g. on issue #464 (and for me during development of PR #466 ) the page content caching is currently not reset when forceReload is set and an `enableCache=invalid` is working only temporarily. That means when I add it to the URL the page looks fine but when I remove it the page looks bugish as before.

**Comment by peuter** [comment]
Ok, the forceReload setting was currently ingored by the caching feature. I created #477 to fix this.

But I cannot reproduce the temporary working cache-invalidation. Could you provide a description how to reproduce that?

**Comment by peuter** [comment]
Please check if #478 fixes this problem too.

**Comment by ChristianMayer** [comment]
Just by looking at the (currently still active) debug messages it seems that I can't invalidate a cache:

Opening the page normally:
```
Current hash: '745316735', cached hash: '745316735'
using cache
```

Adding enableCache=invalid:
```
Current hash: '745316735', cached hash: 'null'
not using cache
```

Opening the page normally again:
```
Current hash: '745316735', cached hash: '745316735'
using cache
```

=> This looks to me as the cache was successfully skipped during the `invalid` run but I can't see whether it was successfully rebuilt.

I would have expected on the normal opening something like
```
Current hash: 'null', cached hash: '745316735'
not using cache
```

=> @peuter  Is this just a misinterpretation by me?

**Comment by peuter** [comment]
`invalid`does not skip caching it just deleted the old cache and saves a new cache when everything got loaded. So on the next run this cache is used. So this works as designed.

**Comment by ChristianMayer** [comment]
ok
