### ISSUE TITLE
Design pitchblack broken

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#472]
The pitchblack design is currently broken:
![cv3](https://cloud.githubusercontent.com/assets/10218721/21963354/990a7c88-db39-11e6-8f65-f9861fabf404.jpg)

**Comment by peuter** [comment]
I cannot reproduce this broken layout, maybe this got fixed by the latest cache fixes?

**Comment by ChristianMayer** [comment]
It's better - but still a bit broken:
![screenshot_20170129_153007](https://cloud.githubusercontent.com/assets/10218721/22404815/b345fba4-e638-11e6-877a-35f6260228b9.png)

**Comment by peuter** [comment]
Well that is a design decision. If it should look like the other designs, pitchblack has to set the default columns in the left navbar to 6. But as this hasn't been done before I assume that this is on purpose. Changing that might break user designs.

**Comment by ChristianMayer** [comment]
As this is a quite history design that was created well before the navbar has appeared and wasn't modified since (IIRC) I guess we are free to change the default to a better value

**Comment by peuter** [comment]
If there are users that use this design with navbars, they would have to re-arrange their colspan in the navbar. Do we want that?
