### ISSUE TITLE
Android Chrome behind proxy: farbtastic and jquery not linked properly

### ISSUE THREAD

**Issue by koendra** [CometVisu/CometVisu#486]
Hi,

When trying to access a cometvisu installation residing behind a reverse proxy (not sure whether this has anything to do with the issue) from an Android Chrome, I get the following error messages in access.conf:
```
::ffff:192.168.1.1 192.168.1.1 - [24/Jan/2017:21:46:43 +0100] "GET /visu_svn/plugins/colorchooser/farbtastic/farbtastic.js HTTP/1.1" 404 345 "http://192.168.1.1/visu_svn/" "Mozilla/5.0 (Linux; Android 6.0.1; E5823 Build/32.2.A.5.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36"
::ffff:192.168.1.1 192.168.1.1 - [24/Jan/2017:21:46:44 +0100] "GET /visu_svn/plugins/diagram/flot/jquery.flot.min.js HTTP/1.1" 404 345 "http://192.168.1.1/visu_svn/" "Mozilla/5.0 (Linux; Android 6.0.1; E5823 Build/32.2.A.5.11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36"
```

This concerns a 0.9.2 installation.

Adding symbolic links to farbtastic.min.js and the flot directory (dep/flot/) solved the issue.

**Comment by ChristianMayer** [comment]
Looking at the code I can't see any place that is referencing `/visu_svn/plugins/diagram/flot/jquery.flot.min.js` - so it'd be interesting where this call is coming from.

General speaking I don't think that this is coming from a reverse proxy - then it'd be an all or nothing. But as everything else seems to work it must be something else.

To be able to work on this issue:

1. Please make sure that you are using the latest version from Git
2. Run with forceReload=true
3. Have a look at the JavaScript console (Ctrl+Shift+I) about what files have a 404 error and where they were requested from

**Comment by koendra** [comment]
Just downloaded 0.10-RC2 and issue has vanished. Thanks for looking into this.

Other things also work much better with this release, thanks for putting so much effort into this!
