### ISSUE TITLE
switch Pressed/Unpressed Mapping with text-only mapping

### ISSUE THREAD

**Issue by Jens-Me** [CometVisu/CometVisu#502]
**Finding:** 
Buttons mit einem Mapping aus Text (und keinem Icon) werden auch im eingeschaltetem Zustand der class 'SwitchUnpressed' zugeordnet. Also das optische "Taste ist gedrückt" fehlt.

**Analyse von peuter**
Das liegt daran, dass für die Entscheidung ob "pressed" oder nicht die gemappedten Werte verglichen werden. Wenn das Mapping immer auf den selben Text gemacht wird, funktioniert das logischerweise nicht, weil die Werte nach dem Mapping immer gleich sind. Wird im Mapping ein Icon verwendet, wird der gemappte Werte intern als Array gespeichert, man hat also 2 Arrays mit dem selben Inhalt (für ein und aus) aber es sind halt unterschiedliche Objekte und somit funktioniert der Vergleich in diesem Fall nur "aus versehen".

Aus meiner Sicht sollte o.g. Vergleich die ungemappedten Werte nutzen, das sollte zuverlässig funktionieren

**Comment by peuter** [comment]
Wurde im aktuellen development-branch gefixt.

@Jens-Me Kannst Du das testen und ggf. dieses Issue schließen, oder falls Du das Problem weiterhin hast ein Beispiel hier angeben mit dem man das reproduzieren kann?

**Comment by peuter** [comment]
Keine Rückmeldung, daher schließe ich das mal
