### ISSUE TITLE
Switch to qooxdoo issues

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#532]
- [x] Slider: Live Updates werden nur ungleichmäßig lang (1 sek?) geschickt
- [x] Seiten-Wechsel: vgl. Demo-Config - die Seiten sollten beim "tiefer"-Navigieren von rechts rein rutschen, kommen aber immer von Links. Außerdem wird da kurz was falsches gezeigt, so dass es kurz flimmert.
- [x] nach bisschen Nutzung hört der Client (eibd-Backend) auf neue Read-Requests abzusetzen, d.h. es gibt auch keine Widget-Updates mehr
- [x] Inline-Diagram: Das Diagram wird mit Achsenbeschriftung dargestellt (sollte ohne sein) und der Popup beim Klick darauf funktioniert nicht
- [x] Bei der Demo-Config funktioniert der Editor nicht mit einem Fehler im XSD-Pfad. (Vermutlich wegen dem Umzug der Configs)
- [x] eibd Backend: Bei einer Anfrage bei der die GAs nicht im Cache liegen und auch nicht auf dem Bus bekannt sind (-> Demo-Configs), kommt eine Fehlermeldung auf der Konsole `SyntaxError: Unexpected token } in JSON at position 0`
- [x] metal Demo: auf der Kommandozeile kommen einige Fehlermeldungen
- [x] Der Cache bekommt nicht mit, dass die generierten Seiten nicht mehr passen => müsste um eine Info bzgl. erzeugender CV Version erweitert werden, da das Problem bei allen zukünftigen Releases passieren kann
- [x] Trick-O-Matic funktioniert nicht mehr, vgl. 2d3d Demo
- [x] demo_flat wirft eine Fehlermeldung `Uncaught TypeError: page.getDomElement(...).children is not a function`
- [x] demo_flat: Die Info-Widets mit den Fenster-Icons skalieren nicht mit
- [x] `generate.py source` sollte ohne weitere Abhängigkeiten laufen
- [x] Demo-Config - Flavours - manche der Subpages lassen sich nicht öffnen

**Comment by peuter** [comment]
Zumindest mit leeren Antworten vom Backend sollte er jetzt klarkommen. Bitte teste mal ob das vielleicht auch eins der anderen Backend/Client Probleme behebt.

**Comment by peuter** [comment]
Ich hab mir jetzt selbst ein Mini-Python-Backend gebastelt, welches mir Daten auf der für die in der 2d3d-Demo benutzte GA liefert `12/7/52` und der Füllstand ändert sich entsprechend. Kann da also kein Problem feststellen.

**Comment by peuter** [comment]
TODOs:
- [ ] ServiceWorker implementieren (siehe #450), AppCache wurde erst gar nicht mit portiert

**Comment by peuter** [comment]
Sind die beiden verbleibenden Probleme (Slider + Fehlende Updates) jetzt eigentlich gelöst?

**Comment by ChristianMayer** [comment]
Ja, die sind gelöst. Ich schau jetzt gerade ob die mir bekannten Last-Minute Issues der 0.10 auch keine Regression bekommen haben

**Comment by peuter** [comment]
Dafür gibts ja neue Tickets, die Themen hier sind erledigt, daher schließe ich das mal.
