### ISSUE TITLE
Firefox bug sets window.ontouchstart and prevents click events from working

### ISSUE THREAD

**Issue by StefanJelner** [CometVisu/CometVisu#533]
Das window-Objekt hat bei Firefox unter bestimmten Konstellationen die ontouchstart-property auf null gesetzt und somit schlägt der Test auf undefined fehl und die CometVisu geht von einem Touchgerät aus.

Mozilla-Bug
https://bugzilla.mozilla.org/show_bug.cgi?id=1081070

CometVisu Version 0.9.2 templatengine.js Zeile 526:

isTouchDevice = !!('ontouchstart' in window) ||    // works on most browsers
!!('onmsgesturechange' in window), // works on ie10

ändern in:

isTouchDevice = (typeof window.ontouchstart !== 'undefined' && window.ontouchstart !== null) ||    // works on most browsers
(typeof window.onmsgesturechange !== 'undefined' && window.onmsgesturechange !== null), // works on ie10

behebt das Problem. Denn es wird nun auf undefined und auf null geprüft. null ist nämlich nicht undefined, sondern ein object in JS.

Ich frage mich allerdings, warum überhaupt zwischen den Devicetypen unterschieden wird, da man mit jQuery bind() mehrere Events gleichzeitig binden kann. Also $('#foo').bind('touchstart mousedown', function() { ... });

**Comment by peuter** [comment]
Also ich kann das Problem nur im Emulationsmodus für Touch-Events reproduzieren. Habe es gerade mal auf einem Laptop mit Touchscreen probiert und da liefert `window.ontouchstart` undefined zurück.

Wie sieht das, denn mit der aktuellen Version der CometVisu aus? Da wurde das Event-Handling überarbeitet und diese Auswertung wird gar nicht mehr benutzt. Ich kann da zumindest keine Probleme feststellen.

Wenn es in der aktuellen Version funktioniert, heißt der Fix: nimm die neue Version. Zumal das Problem ja scheinbar nur im Firefox-Emulationsmodus auftritt und kein Anwenderproblem ist. Und wenn nicht würde ich das so fixen:

```
isTouchDevice = !!window.ontouchstart || // works on most browsers
!!window.onmsgesturechange, // works on ie10
```
Das prüft gegen undefined, null, 0 und leeren String (mindestens).

Und noch zur Vollständigkeit: Ist zwar schon eine Weile her, aber wenn ich mich recht erinnere gibt es Browser sowohl touch als auch mouse-Events feuern, wenn man z.B. einen Mouseclick macht. Wenn man dann auch beide Events hört hat man alles doppelt. Daher die Unterscheidung.

PS: Fürs nächste mal wenn möglich bitte Issues in Englisch formulieren. Deutschen Support gibts eher hier https://knx-user-forum.de/forum/supportforen/cometvisu und hier https://gitter.im/CometVisu/CometVisu_DE

**Comment by ChristianMayer** [comment]
Der Code ist bei der 0.10.0 in die Datei lib/EventHandler.js gewandert (Zeilen 47 und 48), d.h. wenn wir hier ein Problem haben (was ich aktuell nicht nachstellen kann - aber evtl. habe ich keine betroffene Konstellation), sollte dort der Fehler behoben werden.  
Die Lösung von @peuter empfinde ich hier auch als passender.

=> @StefanJelner welche Konstellation zeigt das Problem?
=> @StefanJelner Löst der Vorschlag von @peuter das Problem?
=> @StefanJelner gibt es das Problem auch unter der 0.10.0?

Der Unterschied zwischen den Touch- und den Maus-Events passiert leider nicht aus Spass, sondern weil diese Events sich deutlich unterschiedlich verhalten, insb. in ihrer Reihenfolge. Das gekoppelt mit der Notwendigkeit ein Touch+Hoch/Runter als Scrollen zu implementieren aber gleichzeitig Button-Drücke und Slider-Bewegungen richtig zu handlen haben den etwas komplizierten Code notwendig gemacht.  
Ich bin mir auch nicht sicher, ob der inzwischen optimal ist, aber das wäre dann ein Thema für die 0.11, die ja dann aus Qooxdoo basieren wird.

**Comment by peuter** [comment]
@StefanJelner Updates? Bitte auch mal mit der aktuellen develop-Version (0.11).

**Comment by peuter** [comment]
Da es keine Antwort zu geben scheint -> closed.
