### ISSUE TITLE
Anbindung von MQTT mittels websocket

### ISSUE THREAD

**Issue by brielb** [CometVisu/CometVisu#579]
Hi, meine Idee ist, neben KNX auch andere Geräte einzubinden und dabei MQTT als backbone zu verwenden wie in [https://github.com/mqtt-smarthome](url) vorgeschlagen. Das bedeutete

1.  neues backbone MQTT defnieren
2.  transport über websocket
3.  das Adressschema erweitern, also antatt nur Gruppenadressen 1/2/3 z.B. knx/1/2/3

**Comment by joltcoke** [comment]
Wäre es nicht sinnvoller das openHAB Backend zu nutzen? Dann kannst du entweder dort die MQTT bridge nutzen oder halt die Geräte direkt an openHAB anbinden. Anderenfalls erfindet du mindestens ein Rad neu.

Ich selbst habe unsere FHEM basierte Ferienwohnung per MQTT an obenHAB angebunden. CV als Visu für alles funktioniert perfekt!

**Comment by peuter** [comment]
Sehe ich auch so. Ein Lösung um auch andere Geräte außerhalb von KNX anzusprechen und mit der CometVisu zu bedienen gibt es bereits mit openHAB. openHAB kann auch MQTT, braucht man aber nicht.

Das von Dir verlinkte Github-Projekt ist ja nur ein proposal, ein fertig einsetzbares Produkt hab ich da jetzt nicht gesehen. Wenn es sowas gibt, dann wäre das aus CometVisu Sicht ein weiteres Backend, welches eine neue Transportschicht (MQTT) benutzt. Das müsste dann beides im CometVisu-Client eingebaut werden. Das Problem wäre hier, dass an der Stelle das CometVisu-Protokoll umgangen werden müsste, oder man einen Weg finden müsste das Protokoll über MQTT zu nutzen und das neue Backend müsste das ebenfalls verstehen. Der vordefinierte Weg um ein neues Backend anzubinden ist nämlich diesem das CometVisu-Protokoll beizubringen und nicht der CometVisu beizubringen wir sie mit dem Backend kommunizieren muss.

Und der Vollständigkeit helber noch zu Punkt 3:
In die Addressen kann man beliebige Strings eintragen (für openHAB z.B. die Item-Namen), hier müssten wir also nichts erweitern (außer vielleicht irgendwo einen Syntaxcheck).

**Comment by brielb** [comment]
Hi, danke für Eure Kommentare. BTW Oliver Wagner hat bereits einige Adapter zu MQTT auf github: [https://github.com/owagner]. Fröhliches smartHomen allen ;-)
