### ISSUE TITLE
Reloading of visu fails

### ISSUE THREAD

**Issue by joltcoke** [CometVisu/CometVisu#584]
If you select a different page, the url gets appended by e.g. #id_6_. If you reload the whole visu using the browser reload button, the visu won't load again. Reproduced with Safari and Chrome.

**Comment by peuter** [comment]
The URL appendix (aka anchor) is the current page id and is needed for browser history (make the browsers back button work). When you reload the Visu it opens the same page again, which I think is a nice feature. I reloaded the Visu a thousand times like this, never had a problem. 

So it must be something else. Can you be more specific? What does "the visu won't load again" mean? Are there any errors on the Javascript console?

**Comment by joltcoke** [comment]
Just realised that the issue only occurs with pages that contain a diagram (most of my pages do). There is indeed an error in the logs:

[Error] Error: Invalid dimensions for plot, width = 0, height = 100
	resize (cv-webkit.e55484e93a04.js:5:4401)
	Canvas (cv-webkit.e55484e93a04.js:5:4152)
	setupCanvases (cv-webkit.e55484e93a04.js:5:20751)
	Plot (cv-webkit.e55484e93a04.js:5:11347)
	plot (cv-webkit.e55484e93a04.js:5:52045)
	cv.plugins.diagram.AbstractDiagram.prototype.initDiagram() (cv-webkit.e55484e93a04.js:4:8401)
	(anonymous function) (cv-webkit.e55484e93a04.js:4:12779)
	qx.util.DeferredCall.prototype.call() (cv-webkit.js:213:157850)
	(anonymous function) (cv-webkit.js:213:154889)
	qx.util.DeferredCallManager.prototype.__dp() (cv-webkit.js:213:88712)
	(anonymous function) (cv-webkit.js:213:86799)

The visu only loads the background and show a "-" top left.

**Comment by peuter** [comment]
Hm I still cannot reproduce the error. I have one page with diagram in my config and that one reloads fine.
Would you mind to record a log file and attach it to this issue? (see: http://cometvisu.org/CometVisu/de/latest/manual/colab/index.html#fehlerberichte-mit-log-dateien)

If you don't want to publish you config like that, maybe you can create a stripped down test config, which just enough content to produce the error and record a log with that config.

**Comment by joltcoke** [comment]
I've sent the log file to your gmail address.

**Comment by peuter** [comment]
@joltcoke Thanks for the mail, I could reproduce the error with the logfile you sent. #590 Fixes this error.

**Comment by joltcoke** [comment]
The visu now loads, but the diagrams do not show up, only "loading..." will be shown.
