### ISSUE TITLE
Top of visu missing on Safari

### ISSUE THREAD

**Issue by joltcoke** [CometVisu/CometVisu#585]
If you load the visu in Safari, the topmost approx. 10 pixel are cut off and are simply missing. Doesn't happen in Chrome.

**Comment by joltcoke** [comment]
Only desktop is affected, iOS seems to work fine.

**Comment by peuter** [comment]
Is this specific to a certain config or does it also happen with the demo config? And second question which Safari version?

**Comment by peuter** [comment]
Just tried with Safari 10.1, I cannot confirm that behaviour, demo config looks fine, other configs I tried too.
Might be config specific. Can you provide a simple example config where the problem occurs?

**Comment by joltcoke** [comment]
As soon as I try to strip down the config file, the problem disappears. Looks like it is somehow timing related.

I've attached two log file. One is with the full config (same as I sent to you for the reload issue) and the other is with a slightly modified config (removed 2 invisible pages). At the end of the logs, there are differences.

[log1.txt](https://github.com/CometVisu/CometVisu/files/1018099/log1.txt)
[log2.txt](https://github.com/CometVisu/CometVisu/files/1018100/log2.txt)

**Comment by joltcoke** [comment]
I just reproduced the issue with Chrome by clicking around in the visu for a while. So far I wasn't able to reliably reproduce it again on Chrom.
