### ISSUE TITLE
Left navbar doesn't get replaced

### ISSUE THREAD

**Issue by joltcoke** [CometVisu/CometVisu#588]
My basic layout is: top navbar, which is always the same, below is a left navbar which is page sensitive and gets replaced whenever you switch to a different page. And the actual content on the right.

This setup was working fine before updating to develop. Currently the first loaded left navbar will remain visible forever. The left navbar set by the page will be shown below the initial left navbar. If you switch to a different page, the initial left navbar still remains, the left navbar below will be replaced by the one from the current page.

**Comment by joltcoke** [comment]
Reproduced in Safari and Chrome

**Comment by peuter** [comment]
If your structure is like this:

```
<pages>
 <page name="root">
   <navbar position="left"/>
   <page name="subpage1">
    <navbar position="left"/>
   </page>
   <page name="subpage1">
    <navbar position="left"/>
   </page>
 </page>
</pages>
```
the behaviour you described is the intended one. As the initial navbar is on the root page it is visible on all subpages too. If you don't want that add `scope="1"` to the "root-navbar" then its only visible on the root page and not on the subpages.

If you have another structure please provide an example config ro reproduce the error.

**Comment by joltcoke** [comment]
The initial navBar has scope="0", which was the necessary parameter in previous CV versions. Channing it to scope="1" doesn't make a difference, still broken.

You can use the config I sent you by mail for the reload error to reproduce the problem.
