### ISSUE TITLE
Editor broken in Chrome

### ISSUE THREAD

**Issue by peuter** [CometVisu/CometVisu#605]
Currently no config file can be edited using the build-in editor. The editor stops before loading the the error message:

`The configuration appears to be not valid. Please check with 'check_config.php' for details. Error: 'schema is not valid for this configuration, can not find root-level element pages'`

The cause can be found in the workaround for webkit-based browsers in `editor/lib/Schema.js ` in the fixNamespace method. Deleting this workaround fixes the problem (in Chrome v.60).

@netzkind Can you check if this workaround is still needed or can we just delete it?

**Comment by netzkind** [comment]
I no longer maintain that code.
It's open source: please change if you know what you are doing. 

PS: please don't go around assigning work to people.

**Comment by peuter** [comment]
This assignment wasn't meant as work instruction, just something like "waiting for feedback from".

**Comment by ChristianMayer** [comment]
Opening latest develop version with Chome 55 doesn't shown any problems.

Is that issue fixed with the latest merges?

**Comment by peuter** [comment]
Yes
