### ISSUE TITLE
Widget positioning on 2d page with Backdrop seems to be broken

### ISSUE THREAD

**Issue by peuter** [CometVisu/CometVisu#626]
original report: https://knx-user-forum.de/forum/supportforen/cometvisu/1133276-rückmeldung-zur-aktuellen-entwicklungsversion-nach-umstieg-auf-qooxdoo?p=1136728#post1136728

Can be reproduced with the 2d3d demo config, which shows different behaviour if you:
1. load the start page (#id_) and open the 2d subpage afterwards 
2. load the 2d subpage directly (#id_3_)

In case 1. it seems to look ok, but no backdrop re-positioning is done at all.
In case 2. it does the re-positioning, but it does not look right.

I dont know which one is the expected behaviour as I have no experience with the backdrop stuff, @ChristianMayer could you please check this?

**Comment by ChristianMayer** [comment]
I can't reproduce that issue with the information given above and Chrome 55.

But using demo_flat I can reproduce that the initial page set up (often) is broken:
![screenshot_20171015_002422](https://user-images.githubusercontent.com/10218721/31579850-ba80a3c4-b13f-11e7-96b2-efe0df7ec5a6.png)
Clicking on a sub page (like "Wohnzimmer") and back again shows the content correctly:
![screenshot_20171015_002441](https://user-images.githubusercontent.com/10218721/31579853-d4217006-b13f-11e7-903e-a6ae9688d4a1.png)

**Comment by peuter** [comment]
If I open the demo_flat with `#id_8_` URL suffix and then click on the Page `Übersicht` the widgets are positioned wrong. If I open with no suffix or `id_` it looks ok. Same as described above.

Tested in Chrome 61 and Firefox 56.

**Comment by peuter** [comment]
This bug is still there. If the backdrop page it not the initially loaded one, the widget positioning is wrong. Seems as if the backdrop invalidation hasn't been executed, but that is just a quick guess.
