### ISSUE TITLE
Wrong Height of Pagejump Widget

### ISSUE THREAD

**Issue by robert1978** [CometVisu/CometVisu#645]
The height of the Pagejump-widget is different to other widgets and varying with name-attribute vs. label element. See screenshot and example config attached. Behavior is the same with 0.10.2 and actual build.

1) If text of pagejump widget is applied by using label-element, the text is in line with other widgets, but the widget is slightly larger than rowspan="1". Using rowspan="1" solves this effect as a worksround.

2) If name attribute is used in Pagejump-widget, the widget is significantly larger than rowspan="1". Forcing the height with rospan="1" is no solution, as the text is not in line with other widgets such as 
text- or page-widget.
==> is name attribute required at all??

[visu_config_test_rowspan.txt](https://github.com/CometVisu/CometVisu/files/1393699/visu_config_test_rowspan.txt)

![height_of_pagejump](https://user-images.githubusercontent.com/15055578/31705105-5e6e58fe-b3e4-11e7-8016-c5994718e9d2.png)

**Comment by peuter** [comment]
Fix created a regression -> reverted.
