### ISSUE TITLE
Small pagejump bug 

### ISSUE THREAD

**Issue by robert1978** [CometVisu/CometVisu#654]
Since NightlyBuild from 2017-10-18 the label text of pagejump widget is written over an icon placed in the label. Position of "name" attribute shall start next to icon (used in left navbar), while "label" text is placed below icon (in top navbar).
![pagejump_icon_inlabel](https://user-images.githubusercontent.com/15055578/31851563-99b4d312-b668-11e7-97c9-d7c0ed8ca7e6.png)
[visu_config_test_bug_pagejump.txt](https://github.com/CometVisu/CometVisu/files/1404068/visu_config_test_bug_pagejump.txt)

**Comment by peuter** [comment]
Introduced with b26ee2a979966405c7f780420d21808a9f617d65
I tend to revert this commit as evenry change here seems to break something else.

**Comment by robert1978** [comment]
For me ok to revert.
Was more a small visual issue than a bug.

**Comment by peuter** [comment]
I found more height problems during investigation. A simple revert doesn't fix the problem.

**Comment by peuter** [comment]
Ok after some more testing I reverted the old fix. We have to live with the small visual issues.
The only way to solve this is a re-creation of the metal design from scratch. With the current version it does not seem to be possible to change the CSS rules around the widgets margin/paddings without creating a regression.
