### ISSUE TITLE
Slider not allways working

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#655]
As described in #610 the slider doesn't always send it's new value when clicked on the slider bar (long polling backend, not sending confirmed by network pane).
When the handle is dragged the new values are mostly sent - but sometimes they are also missing.

**Comment by peuter** [comment]
Can you provide a log for this issue? I am not able to reproduce the problem.

**Comment by ChristianMayer** [comment]
-> Mail
