### ISSUE TITLE
Is high traffic to 151.101.0.162 expected?

### ISSUE THREAD

**Issue by meatballhat** [CometVisu/CometVisu#689]
Hello :wave:  I am one of the engineers at Travis CI who's responsible for build infrastructure.  I recently added some logging for when certain network usage levels are breached, and a recent job for this repo came up (https://travis-ci.org/CometVisu/CometVisu/jobs/353550128).  Is anyone able to help me understand why this job is creating over 100 connections/min to 151.101.0.162 (which does not reverse resolve for me).  Thank you! :sparkling_heart:

**Comment by ChristianMayer** [comment]
Hi @meatballhat to be honest: I don't know.
But I can speculate: 151.101.0.162 belongs to https://www.fastly.com/ and they say they are also an CDN.
So unless I know more I guess that the automated testing running the CometVisu in a headless Chrome might call a resource from the net that is hosted at fastly.

@peuter do you have more insight? Might it be an internal call from the Qooxdoo framework? (The development console dosn't show me an external connection attempt so I don't think that's the case). Might it be the Chrome?

**Comment by meatballhat** [comment]
:man_facepalming: it's totally Fastly.  I assume we're going to add some ignore rules for well-known CDNs.  Thanks for your help!

**Comment by peuter** [comment]
As the build that caused the traffic included an update to an npm dependency, I assume that downloading the update caused the traffic. Its more than likely that npm is using a CDN. But these are all unverified assumptions.
