### ISSUE TITLE
Slider writes just read value

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#696]
A config with a slider and addresses like:
```
        <address transform="DPT:5.010" mode="write">1/2/52</address>
        <address transform="DPT:5.010" mode="read">1/3/52</address>
```
When an external event creates a telegram on 1/3/52 the slider resends exactly that value on 1/2/52 which is wrong.

Expected would be that a recieved packed doesn't trigger a message from the visu. And definitely not a message with exactly the same (binary) value.

**Comment by ChristianMayer** [comment]
#697 didn't close this issue :(

**Comment by peuter** [comment]
Really? The test I've added reproduced the behaviour and the PR fixed the test. Can you provide a unit test for this error? Or send me a log file?
