### ISSUE TITLE
Feature request: walk through a list of items and show them based on state

### ISSUE THREAD

**Issue by pdcemulator** [CometVisu/CometVisu#699]
I want to show a list of items based on status. For example a list of open windows and dont show closed windows.

My usecase is a wall mounted tabled running visu in my floor to identify open windows before leaving the house. Showing the status of all windows consumes much space.

**Comment by peuter** [comment]
You could use the InfoAction-Widget (http://cometvisu.org/CometVisu/de/latest/manual/config/widgets/infoaction/index.html) to show the Number of open windows and combine it with a PageJump, which leads to a page with all window states. Would that be feasible for your usecase?

**Comment by pdcemulator** [comment]
issue closed because I no longer use CometVisu
