### ISSUE TITLE
Refactor manager.php

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#722]
It has grown too much (especially with the TR-064 plugin)

**Comment by peuter** [comment]
I am currently working on a replacement for all the php stuff (thats not part of a plugin). The main purpose it to reduce the code that needs to run on the server as much as possible. The "new" Backend-Code just provides a REST-API with basic CRUD operations for files/folders in the config-folder and support for the hidden configuration modifications.
The new manager is something like a Web-IDE, where you can code your CSS/JS/Config-XML files, having all the fancy stuff like code-completion, validation. Quite nice already at this early stage of development. Still a long way to go but worth the effort I think.
The current XML-Editor is currently embedded as an IFrame and feels like an alien in there. I guess it needs some love too in the near future as mentioned in #782.

**Comment by ChristianMayer** [comment]
As already written somewhere else, we should have a sort of CI for the CV "support" pages. Currently it's very cluttered: one design for the homepage, one for the manual, one for the API (ok, users don't go there), one for the manager, one for the graphical editor, one for the text editor...

Personally I don't have a CI yet, except perhaps the homepage (which wasn't really desinged, it just "happened")

**Comment by peuter** [comment]
Done with the new manager
