### ISSUE TITLE
Move user changeable files in one directory

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#738]
The user changeable files like configs but also e.g. custom.css should all be located in one directory to make it easy to migrate to a new version, create a Docker container where those files are located in a Volume, ...

This would also solve: https://forum.timberwolf.io/viewtopic.php?p=2409#p2409

**Comment by peuter** [comment]
Might be solvable without too many changes?!

If you create a folder, e.g. called "overlay" in the config folder (which is a docker volume) enable mod_rewrite and add an .htaccess to the docker container. This .htaccess is filled with rules that serve files from the "overlay"-folder first and only the "normal" files as fallback.

For example (from the cometvisu inside docker point-of-view):
1. HTTP-Request to `resource/designs/metal/custom.css`:
  * serve file `resource/config/overlay/designs/metal/custom.css` if it exists
  * server file `resource/designs/metal/custom.css` otherway

I think that would be a flexible way and also allow custom plugins, or anything else to be overridden.

**Comment by ChristianMayer** [comment]
Closed by #788
