### ISSUE TITLE
Icon list broken after release process

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#769]
Opening the icon list via source is fine:
![screenshot_20181212_225832](https://user-images.githubusercontent.com/10218721/49901518-ad71cf80-fe61-11e8-927f-93ea19fa6712.png)

But opening the same list from the latest testing container looks (nearly) like:
![screenshot_20181212_225951](https://user-images.githubusercontent.com/10218721/49901521-aea2fc80-fe61-11e8-991e-1e9d28d805ee.png)

It is only "nearly" as I added a `viewBox` attribute at the only icon that is showing up:
![screenshot_20181212_230115](https://user-images.githubusercontent.com/10218721/49901610-e90c9980-fe61-11e8-8381-37b3c2b5d555.png)

As the list from source has there `viewBox` everywhere and the built list none and the icon appears when I add the entry myself I recon this must be the source of the display issue.
Still open (and to me completely unclear) is why the source and build versions are creating these DOM differences.

**Comment by ChristianMayer** [comment]
This problem seems to break `resource/icon/knx-uf-iconset.svg` as all other uses of these icons (manager, the visu itself) are also broken.

**Comment by peuter** [comment]
Very strange that no one noticed this before. The svgmin-job that caused the viewBox removal hasn't been changed since 2016.
