### ISSUE TITLE
Editor 2.0

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#782]
The bring the editor to the next level a few points should be done:

- [ ] _internal:_ Make code `strict`
- [ ] _internal:_ Separate view and logic, e.g. use a tree widget
- [ ] _visible:_ Allow drag&drop to move elements around (instead of the current `sort`)
- [ ] _visible:_ make it more mobile device friendly (-> no context menu to create new elements)
- [ ] _visible:_ Link editor with preview to that the use immediately sees where the selected element is in the visu
- [ ] _visible:_ replace all alert boxes with less disturbing/distracting feedback
- [ ] _visible:_ Allow language switch and implement mulitlanguage

**Comment by peuter** [comment]
I guess this is done with the new xml editor
