### ISSUE TITLE
Flow-o-matic doesn't start

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#864]
Using e.g. demo_flat the switch at "Technik" can stop the flow-o-matic but doesn't start it again.
Also switching pages seem to brake the flow-state

**Comment by peuter** [comment]
Changed the milestone as this is definitely a bug that should not be released with 0.11.0.

**Comment by ChristianMayer** [comment]
#866 helped.
But still broken: when the flow is stopped by the GA, page is changed away and then shown again the flow should still be stopped but it is running again
