### ISSUE TITLE
List of commits to be cherry-picked for 0.11.1

### ISSUE THREAD

**Issue by peuter** [CometVisu/CometVisu#910]
- [x] da0373ac6b9187d367473a326e00cb8953f6ff3c [fix template rendering]
- [x] d8a11a94b3644e2d97b6808bb2e114d0084fdbd8 [influxfetch could not handle series generated by smarthomeNG containing  a dot in series name]
- [x] d8d21b967e2e595baa72c5342c3fbdf7b46ace14 [remove duplicate fakeserver initialization and add some metadata to the fake xhr responses]
- [x] #909
- [x] #912
- [x] #913
- [x] #914
- [x] #915

**Comment by ChristianMayer** [comment]
Is 42876f3 [fix openweathermap error onload and improve appearance in demo mode] really needed for a cherry pick?
The Openweathermap plugin was changed in 0.12 and not already in 0.11

**Comment by peuter** [comment]
You're right, my fault. This commit is not needed.
