### ISSUE TITLE
Problems with Slider and Colorchooser with OH2 Backend

### ISSUE THREAD

**Issue by rssprinter** [CometVisu/CometVisu#936]
Hi,

ich habe seit langem OH2 mit Habpanel laufen.
Jetzt hab ich CometVisu installiert configuriert Habe nun folgende Probleme:
- Der Slider für rollershutter Items funktioniert nur 1x danach sendet er keine Werte mehr.
- Das colorchooser plugin funktioniert nicht, obwohl ich ein color item übergebe und den Variant auf "rgb´" setze.

Kann irgendjemand hier helfen?

Matthias

**Comment by peuter** [comment]
Hm, seltsam. Ich benutze beides mit openHAB2 und es funktioniert. Da müsstest Du mal Deine Config-Datei zur Verfügung stellen, oder zumindest eine minimal-Config mit den entsprechenden Widgets.
Oder aber direkt eine Replay-Datei aufnehmen und dort die Widgets bedienen, so dass der Fehler auftritt (siehe: https://www.cometvisu.org/CometVisu/de/latest/manual/colab/index.html#fehlerberichte-mit-replay-dateien)

**Comment by rssprinter** [comment]
Das Problem mit dem Slider konnte ich mittlerweile lösen. Habe bei transform von rollershutter auf dimmer gewechselt, danach hat es funktioniert.

Hier die Auszüge aus der config:
		<plugins>
			<plugin name="colorchooser" />
			<plugin name="tr064" />
			<plugin name="upnpcontroller" />
			<plugin name="gauge" />
			<plugin name="clock" />
			<plugin name="openweathermap" />
			<plugin name="strftime" />
			<plugin name="diagram" />
		</plugins>

...
				<colorchooser>
					<layout colspan="2" />
					<label>
						<icon name="light_led_stripe_rgb" />
						LED TV
					</label>
					<address transform="OH:color" variant="rgb" mode="readwrite">Light_GF_Living_TV</address>
				</colorchooser>



Anbei meine config als txt Datei
[visu_config_Zugspitz_13.txt](https://github.com/CometVisu/CometVisu/files/3167732/visu_config_Zugspitz_13.txt)

**Comment by rssprinter** [comment]
Wollt as thema nicht schließen

**Comment by peuter** [comment]
Ja, der ColorChooser hat einen Bug. Er funktioniert nur, wenn er auf der Seite ist, die als erstes geladen wird. Daher war mir das Problem beim ersten Test nicht aufgefallen.

**Comment by rssprinter** [comment]
Habs ausprobiert. Auf der ersten Seite läuft es super so wie ich es erwartet habe.

**Comment by ChristianMayer** [comment]
Mit dem KNX Backend habe ich da keine Probleme beim ColorChooser gehabt.
Aber aber trotzdem mal #937 gemerged.

**Comment by peuter** [comment]
Dürfte gelöst sein

**Comment by rssprinter** [comment]
Hallo Tobias,

 

bei mir geht’s nur wenn ich eine Unterseite mit F5 neu lade.

Bin mir aber auch nicht sicher ob das nicht vorher auch schon so war.

 

Muss ich noch was spezielles einspielen oder reicht das automatische Neuladen beim Starten von openhab?

 

 

Von: Tobias Bräutigam <notifications@github.com> 
Gesendet: Mittwoch, 26. Juni 2019 21:21
An: CometVisu/CometVisu <CometVisu@noreply.github.com>
Cc: rssprinter <jung@manage2change.de>; State change <state_change@noreply.github.com>
Betreff: Re: [CometVisu/CometVisu] Problems with Slider and Colorchooser with OH2 Backend (#936)

 

Dürfte gelöst sein

**Comment by peuter** [comment]
Der auto-download ist nur dafür gedacht die CometVisu zu installieren, wenn man das noch nicht gemacht hat. Der macht kein automatisches Upgrade, das musst du selbst machen. Aber der Fix ist erstmal nur Teil der Entwicklungsversion und wird dann Teil des nächsten Releases (0.11.2) was noch nicht released ist. Da musst Du erst noch etwas warten (keine Ahnung wie lange).
