### ISSUE TITLE
pushbutton missing format attribute

### ISSUE THREAD

**Issue by Zugschlus** [CometVisu/CometVisu#940]
Hi,

given the following code:

```
              <pushbutton downValue="30" upValue="30">
                <layout colspan="1"/>
                <address transform="DPT:5.001" mode="readwrite">4/2/23</address>
              </pushbutton>
```

the pushbutton reads back the status and displays it unformatted. This, for example means, that numbers are given with 14 decimals which, for example, does not make any sense for a percentage.

![Screenshot_20190526_151137](https://user-images.githubusercontent.com/1712376/58382350-5dc73080-7fc9-11e9-808a-bb099315b940.png)

A format attribute would help here, and probably with other widgets as well.

Greetings
Marc

P.S.: I'm filing this as an issue because I tried discussing this on the knx-user-forum and on the timberwolf forum and got nothing but RTFM messages back. Since I didn't find the information there, this is either a missing feature or a usability issue.

**Comment by peuter** [comment]
The pushbutton (and other widgets) already supports the format feature. The only thing that is currently missing is that the format attribute is allowed in this widget in the schema definition.

If you use a Text-Editor and do not care about a valid Config-File you can just add the format attribute there, should work out of the box. PR #944 changes the schema, to allow the attribute to be added in the XML-Editor (and show that information in the documentation)
