### ISSUE TITLE
XML editor doesn't grok more advanced moustache usage

### ISSUE THREAD

**Issue by Zugschlus** [CometVisu/CometVisu#942]
Hi,

I would like to write the following code (simplified):

```
      <template name="rolladen">
        <group align="left" flavour="antimony" name="{{name}}">
          <layout colspan="6"/>
          <trigger value="1" mapping="AufAbSymbol" align="center">
            <layout colspan="1"/>
            <address transform="DPT:1.008" mode="readwrite">{{ AddrLang }}</address>
          </trigger>
          <group flavour="black" nowidget="true" name="Höhe anfahren">
            <slide min="0" max="100" step="1" format="%d%%">
              <layout colspan="3"/>
              <address transform="DPT:5.001" mode="readwrite">{{ AddrWert }}</address>
              <address transform="DPT:5.001" mode="read">{{ AddrStatus }}</address>
            </slide>
            {{#CatflapWert}}
            <pushbutton downValue="{{ CatflapWert }}" upValue="{{ CatflapWert }}" mapping="Catflap">
              <layout colspan="1"/>
              <address transform="DPT:5.001" mode="readwrite">{{ AddrWert }}</address>
            </pushbutton>
            {{/CatflapWert}}
          </group>
        </group>
      </template>
```

In prose, I only want the pushbutton to be rendered when a CatflapWert is given.

The XML editor doesn't like that, flagging the second "group" line as an error ("Element 'group': Character content other than whitespace is not allowed because the content type is 'element-only'.")

Greetings
Marc

**Comment by peuter** [comment]
I have no idea how to solve that problem. Basically you have to either disable the syntax check in the template region completety (which is no option IMHO) or find a way to augment the given XSD-Schema to allow TextNodes everywhere in the template section (I have no idea if this is even possbile without defining everything twice.
We need a real XSD expert to solve this.

**Comment by peuter** [comment]
It turns out, that the template sections also work when you add them as comment, e.g. `<!-- {{#CatflapWert}} -->` and that is a valid config file and accepted by the Text editor.

**Comment by Zugschlus** [comment]
Thanks for helping here, this does indeed work and it also causes moustache to handle things correctly. This should be in the documentation, but the entire template stuff does not seem to be in the manual yet at all.

**Comment by peuter** [comment]
Yes it is: https://www.cometvisu.org/CometVisu/de/0.11/manual/config/xml-format.html#templates
But the part with the sections is indeed missing.
