### ISSUE TITLE
Please consider auto-merging address objects with same address and different modes

### ISSUE THREAD

**Issue by Zugschlus** [CometVisu/CometVisu#945]
Hello,

this:

```
<switch mapping="OnOff_Licht" styling="GreyGrey" bind_click_to_widget="false">
  <label>Handwerker</label>
  <address transform="DPT:1.001" mode="read">1/1/152</address>
  <address transform="DPT:1.001" mode="write">1/1/152</address>
</switch>
```

Doesnt work as expected (always sends 'off', never changes),  which comes unhandy when this code pattern is used in a template. One needs to write explicitly:

```
<switch mapping="OnOff_Licht" styling="GreyGrey" bind_click_to_widget="false">
  <label>Handwerker</label>
  <address transform="DPT:1.001" mode="readwrite">1/1/152</address>
</switch>
```

Would it be possible to automatically do this merge whien to address elements are given with the same address but different modes? This would greatly ease templating.

Greetings
Marc

**Comment by peuter** [comment]
It should you expect it, if it does not this is a bug. I will habe a look at it.
