### ISSUE TITLE
Docker container should be able to limit log

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#949]
See https://forum.timberwolf.io/viewtopic.php?f=31&t=1156&p=11715#p11699

**Comment by peuter** [comment]
The linked post is not public, all I see is a login form. So a little bit more information is required here.

**Comment by ChristianMayer** [comment]
> [...]
> Mir ist aufgefallen, dass das Log für die CV für einen Tag etwa 450 MB braucht. Wenn alte Logs automatisch komprimiert oder gelöscht werden, kann es sein dass plötzlich wieder mehr Speicherplatz frei ist.
>
> Akutell sehe ich es nicht als Problem, aber die Frage wäre ob es nötig ist jeden Request an die CV zu speichern.
> Chris M. Wie siehst du das? Vielleicht eine ENV-Einstellung um das Log-Level anzupassen?

**Comment by ChristianMayer** [comment]
See also: https://forum.timberwolf.io/viewtopic.php?f=31&t=1236&p=12524#p12517

**Comment by ChristianMayer** [comment]
The current containers have the environment variable `ACCESS_LOG` to show that log as well or not.
