### ISSUE TITLE
List of commits to be cherry-picked for 0.11.3

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#956]
- [x] #955 
- [x] #971 (in #972)
- [ ] #970 - at least check whether it should be cherry picked - note (10.11.19): that plugin seems to be broken at 0.11.x so it might need a backport from 0.12
- [ ] #975 
- [x] #978 
- [ ] #986
- [x] #987

And to be cherry picked in develop (0.12):
- [ ] #1002

**Comment by ChristianMayer** [comment]
- [ ] #970 - at least check whether it should be cherry picked

**Comment by ChristianMayer** [comment]
[ ] #975

**Comment by ChristianMayer** [comment]
- [ ] #978

**Comment by peuter** [comment]
- [ ] #986

**Comment by peuter** [comment]
I just merged all comments into the first one, because in the issue list only the tasks from the initial comment are shown and this issue seemed to have all tasks resolved.

**Comment by ChristianMayer** [comment]
Next release is 0.12 - so this issue isn't required anymore
