### ISSUE TITLE
2D3D Demo broken

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#988]
See also https://forum.timberwolf.io/viewtopic.php?f=37&t=1935&p=20805#p20793

**Comment by peuter** [comment]
It is not broken, you have to call the URL with `testMode=true` to make it work, otherwise the backend has to handle the changes you trigger and send them back to the CometVisu to show them.

**Comment by ChristianMayer** [comment]
I was testing it with develop on my local machine and there I get an error message at the console.
So far I didn't dig too deep into it but is seems that at least the backend URI is wrong as the second "l" (i.e. the "l" for the SVG) goes to "https://timberwolfX.local/cgi-bin/l?u=demo_user" although "https://timberwolfX.local/proxy/visu/cgi-bin/l?u=demo_user" would have been correct (and which is used from the CV itself)

**Comment by peuter** [comment]
Ah ok, got it.
